export function setupFixture(){
  window.fixtureMode=window.sessionStorage?.getItem('syntheticSourcePlacement')||'field';window.readRequests=[];window.writes=[];window.authSubject='synthetic-owner';
  window.fixtureDevices=[{id:11,unit_key:'RANGER 022',device_name:'RANGER 022 Camera 1',device_type:'camera',monitoring_profile:'ranger',organization:'ROOT',source_status:'offline',source:'vigilant_control_center',source_last_seen_at:new Date().toISOString(),activation_state:'active',public_ip:'192.0.2.11',expected_ports:[80]},
    {id:12,unit_key:'SNIPER 00312.2',device_name:'SNIPER 00312.2 Recorder',device_type:'NVR',monitoring_profile:'sniper',organization:'Old provider yard',source_status:'offline',source:'2026_unit_tracker',source_last_seen_at:new Date().toISOString(),activation_state:'active',public_ip:'192.0.2.12',expected_ports:[80]},
    {id:13,unit_key:'SOLAR STAND 72 001',device_name:'Support equipment',device_type:'tracker_unit',organization:'ROOT',activation_state:'active',source:'tracker_evidence'}];
  window.snapshotFixture=()=>{
    const shop=fixtureMode==='shop',owner=fixtureMode==='owner',row={id:'11111111-1111-4111-8111-111111111111',unitNumber:'RANGER 022',readOnly:false,currentLocationType:shop?'shop':'field',status:shop?'readiness_unverified':'field',site:shop?'SHOP / ROOT':owner?'Owner current site':'Approved mHelp job site',address:shop?'':owner?'99 Owner Road, Testville, TX 75001':'10 Source Road, Testville, TX 75001',importedPlacement:shop?'SHOP':'FIELD',importedInstallation:{entityKind:'native',nativeUnitId:'11111111-1111-4111-8111-111111111111',sourceRevision:'revision-current',eventId:'event-current'}};
    if(owner)Object.assign(row,{placement:'FIELD',placementSource:'owner',placementAuditId:'101',placementUnitKey:'RANGER 022',locationVerification:'owner_verified',locationVerifiedAt:new Date().toISOString(),locationHistoryId:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',latitude:32.123,longitude:-96.234,hasUnitGps:true});
    const alias={...row,id:'22222222-2222-4222-8222-222222222222',unitNumber:'SNIPER 312.2',site:'Alias verified site',address:'22 Alias Road, Testville, TX 75001',currentLocationType:'field',placement:null,placementSource:null,placementAuditId:null,placementUnitKey:null};
    if(fixtureMode==='inactive')Object.assign(row,{currentLocationType:'inactive',status:'inactive',site:'INACTIVE / DO NOT USE',address:null,addressSource:null,addressUpdatedAt:null,placement:null,placementSource:null,placementUnitKey:null,placementAuditId:null,placementUpdatedAt:null,latitude:null,longitude:null,coordinateSource:null,importedPlacement:'INACTIVE',importedInstallation:{entityKind:'equipment_unit',nativeUnitId:row.id,productId:'12345',sourceRevision:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',eventId:'1',nativeGuardSha256:'a'.repeat(64),sourceFileSha256:'b'.repeat(64),sourceRowSha256:'c'.repeat(64),placement:'INACTIVE'}});
    const inventory=[row,alias],items=inventory.filter(r=>r.currentLocationType==='field');
    return {items,inventoryItems:inventory,summary:{fieldUnits:items.length},placementReviews:[],generatedAt:new Date().toISOString()};
  };
  window.healthFixture=()=>({evidenceVersion:2,identityVersion:1,rows:fixtureDevices.map(d=>({id:d.id,unit:d.unit_key,evidence:{kind:'provider',source:'Star4Live'},trackerOnly:false})),unitIdentities:[{unitId:'11111111-1111-4111-8111-111111111111',unitNumber:'RANGER 022',kind:'native_provider',deviceIds:['11'],unitKeys:['RANGER 022'],proof:'a'.repeat(64)}],ownerConfirmedIdentityVersion:1,ownerConfirmedUnitIdentities:[{unitId:'22222222-2222-4222-8222-222222222222',unitNumber:'SNIPER 312.2',kind:'owner_confirmed_native',deviceIds:['12'],unitKeys:['SNIPER 00312.2'],proof:'b'.repeat(64)}],identityWarnings:fixtureMode==='warning'?[{unitId:'11111111-1111-4111-8111-111111111111',reason:'Source revision changed',deviceIds:['11'],unitKeys:['RANGER 022']}]:[]});
  window.supabase={createClient:()=>({auth:{getSession:async()=>({data:{session:{user:{id:authSubject},access_token:'synthetic-only'}}}),onAuthStateChange:callback=>{window.authChange=callback;return{data:{subscription:{unsubscribe(){}}}}}},rpc:async(name,args)=>{readRequests.push({name,args});if(name==='owner_camera_unit_placement_state_v2'&&window.holdPlacementState)await new Promise(r=>window.releasePlacementState=r);return {data:name==='cos_verified_fleet_capabilities_v1'?{fleetRead:true,fleetPlacementEdit:true,fleetConnectionEdit:true}:name==='owner_camera_unit_placement_state_v2'?{unitKey:args.p_unit_key,placement:'SHOP',siteLabel:'',streetAddress:'',auditId:null,canMove:true}:null};},functions:{invoke:async(name)=>{readRequests.push({name});return{data:{configured:true}}}},from(table){const q={filters:[],one:false,select(){return q},eq(k,v){q.filters.push([k,v]);return q},ilike(k,v){q.filters.push([k,v]);return q},in(){return q},order(){return q},range(){return q},limit(){return q},single(){q.one=true;return q},maybeSingle(){q.one=true;return q},update(){writes.push(table);throw Error('Synthetic write forbidden')},then(done){let data=table==='profiles'?{active:true,role:'owner'}:table==='camera_devices'?fixtureDevices.filter(d=>q.filters.every(([k,v])=>d[k]===v)):table==='camera_health_current'?[{camera_device_id:12,overall_status:'offline',confirmed_outage:true,checked_at:new Date().toISOString(),consecutive_failures:3}].filter(h=>q.filters.every(([k,v])=>h[k]===v)):[];if(q.one&&Array.isArray(data))data=data[0]||null;return Promise.resolve({data}).then(done)}};return q;}})};
}
