import assert from 'node:assert/strict';import {test,before,after,beforeEach} from 'node:test';import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';import {setupMembershipFixture,membershipBaseSql,id,members,actor} from '../legacy/tests/mhelp-shared-membership-fixture.mjs';
let db;before(async()=>{db=new PGlite();await db.exec('create role anon;create role authenticated;create role service_role bypassrls;');});after(async()=>db.close());beforeEach(async()=>setupMembershipFixture(db));
const reconcile=(rev,source,roster)=>db.query('select cos_mhelp_intake.reconcile_memberships_v1($1,$2,$3,$4::jsonb) v',[id(100),rev,source,JSON.stringify(roster)]);
const resolve=(n,prep=null)=>actor(db,n,'select cos_mhelp_intake.resolve_participant_v1($1,$2,$3) v',[id(n+10),id(n),prep]);
test('one canonical work order has exact multi-IT/multi-Service immutable memberships and inert replay',async()=>{assert.equal((await db.query('select count(*)::int n from cos_mhelp_intake.participants')).rows[0].n,4);assert.equal((await reconcile(2,'revision-1',members())).rows[0].v.state,'unchanged');const v=(await resolve(1)).rows[0].v;assert.equal(v.work_order_id,id(100));assert.equal(v.department,'it');assert.equal(v.writable,true);await assert.rejects(db.exec(`update cos_mhelp_intake.participants set legacy_user_id='${id(9)}' where assignment_id='${id(11)}'`),/immutable/);});
test('withdrawal preserves participant history and denies current authority without touching coworker audit rows',async()=>{const before=(await db.query('select * from public.workflow_checkpoints')).rows;await reconcile(2,'revision-2',members([1,2,3]));assert.equal((await db.query("select count(*)::int n from cos_mhelp_intake.participants where state='withdrawn'")).rows[0].n,1);await assert.rejects(resolve(4));assert.deepEqual((await db.query('select * from public.workflow_checkpoints')).rows,before);await assert.rejects(reconcile(2,'revision-3',members()),/revision_conflict/);});
test('reused revision with changed roster is rejected and current profiles/assignment identities are independently checked',async()=>{await assert.rejects(reconcile(2,'revision-1',members([1,2,3])),/source_revision_conflict/);await db.exec(`update public.profiles set active=false where user_id='${id(1)}'`);await assert.rejects(resolve(1),/not_current/);await db.exec(`update public.profiles set active=true where user_id='${id(1)}';update public.job_assignments set assignee_user_id='${id(2)}' where id='${id(11)}'`);await assert.rejects(resolve(1),/not_current/);});
test('cancelled markers deny even assigned status; completed current membership remains readable for downstream installation',async()=>{await db.exec(`update public.job_assignments set cancelled_at=now() where id='${id(11)}'`);await assert.rejects(resolve(1),/not_current/);await db.exec(`update public.job_assignments set status='completed',completed_at=now() where id='${id(13)}'`);const v=(await resolve(3)).rows[0].v;assert.equal(v.writable,false);assert.equal((await actor(db,3,'select cos_mhelp_intake.lock_participant_v1($1,$2,null,false) v',[id(13),id(3)])).rows[0].v.membership_id,v.membership_id);});
test('canonical prep binding is exact, atomic, shared and never creates coworker lifecycle changes',async()=>{await db.exec(`insert into public.prep_tickets values('${id(200)}','SYN-42','draft','Synthetic');update public.job_assignments set prep_ticket_id='${id(200)}',status='started',started_at=now() where id='${id(11)}'`);await actor(db,1,'select cos_mhelp_intake.bind_prep_v1($1,$2,$3,$4)',[id(100),id(11),id(1),id(200)]);assert.equal((await resolve(2,id(200))).rows[0].v.prep_id,id(200));assert.equal((await db.query('select status from public.job_assignments where id=$1',[id(12)])).rows[0].status,'assigned');await assert.rejects(actor(db,1,'select cos_mhelp_intake.lock_participant_v1($1,$2,$3)',[id(11),id(1),id(200)]),/scope_unavailable/);await assert.rejects(db.exec(`update cos_mhelp_intake.work_orders set prep_ticket_id=null`),/immutable/);});
test('source classifier fails closed for broken bindings and release refuses unregistered manual assignment',async()=>{assert.equal((await db.query('select cos_mhelp_intake.has_source_binding_v1($1,null) v',[id(11)])).rows[0].v,true);await db.exec(`insert into public.job_assignments(ticket_no,assigned_role,assigned_by,assigned_by_name) values('SYN-42','service','${id(9)}','Synthetic')`);await assert.rejects(resolve(1),/untracked_assignment/);});
test('private schema/tables/helpers deny all application roles and no public function is added',async()=>{for(const role of ['anon','authenticated','service_role']){await db.exec('set role '+role);await assert.rejects(db.query('select * from cos_mhelp_intake.participants'),/permission denied/);await assert.rejects(db.query("select cos_mhelp_intake.has_source_binding_v1(null,null)"),/permission denied/);await db.exec('reset role');}assert.equal((await db.query("select count(*)::int n from pg_proc where proname like 'camera_mhelp%' ")).rows[0].n,0);});
test('department claim requires same-transaction pristine admission and preserves genuine department scope',async()=>{
 await db.exec(`insert into cos_mhelp_intake.work_orders(id,portal_id,ticket_id,ticket_number) values('${id(101)}','17','43','SYN-43');insert into public.job_assignments(id,ticket_no,created_from,assigned_role,assignment_scope,assigned_by,assigned_by_name) values('${id(15)}','SYN-43','mhelpdesk_service_intake','it','department','${id(9)}','Synthetic');select cos_mhelp_intake.register_assignment_v1('${id(101)}','${id(15)}','it',null);`);
 await assert.rejects(actor(db,1,'select cos_mhelp_intake.record_department_claim_v1($1,$2)',[id(15),id(1)]));
 await actor(db,1,`begin;select cos_mhelp_intake.prepare_department_claim_v1('${id(15)}','${id(1)}');update public.job_assignments set assignee_user_id='${id(1)}',assignee_name='Synthetic 1',status='started',started_at=now(),claimed_at=now(),updated_at=now() where id='${id(15)}';select cos_mhelp_intake.record_department_claim_v1('${id(15)}','${id(1)}');commit;`);
 assert.equal((await db.query('select origin from cos_mhelp_intake.participants where assignment_id=$1',[id(15)])).rows[0].origin,'local_department_claim');assert.equal((await actor(db,1,'select cos_mhelp_intake.resolve_participant_v1($1,$2,null) v',[id(15),id(1)])).rows[0].v.department,'it');
});
test('completed or cancelled marker on an assigned queue cannot acquire admission',async()=>{await db.exec(`insert into cos_mhelp_intake.work_orders(id,portal_id,ticket_id,ticket_number) values('${id(101)}','17','43','SYN-43');insert into public.job_assignments(id,ticket_no,created_from,assigned_role,assignment_scope,assigned_by,assigned_by_name) values('${id(15)}','SYN-43','mhelpdesk_service_intake','it','department','${id(9)}','Synthetic');select cos_mhelp_intake.register_assignment_v1('${id(101)}','${id(15)}','it',null);update public.job_assignments set completed_at=now() where id='${id(15)}';`);await assert.rejects(actor(db,1,'select cos_mhelp_intake.prepare_department_claim_v1($1,$2)',[id(15),id(1)]),/not_pristine/);});
test('removed crew cannot be withdrawn around a manual/start/completion change',async()=>{await db.exec(`update public.job_assignments set notes='Synthetic manual note' where id='${id(14)}'`);await assert.rejects(reconcile(2,'revision-2',members([1,2,3])),/work_changed/);assert.equal((await db.query("select state from cos_mhelp_intake.participants where assignment_id=$1",[id(14)])).rows[0].state,'active');});

test('installation preserves unrelated preexisting schema usage and function/table ACLs',async()=>{await db.exec(membershipBaseSql());await db.exec("create schema cos_mhelp_intake;grant usage on schema cos_mhelp_intake to authenticated;create table cos_mhelp_intake.canary(value integer);grant select on cos_mhelp_intake.canary to authenticated;create function cos_mhelp_intake.canary_v1() returns integer language sql as $$select 7$$;grant execute on function cos_mhelp_intake.canary_v1() to authenticated");await db.exec(await readFile(new URL('../legacy/mhelp-shared-memberships-proposal.sql',import.meta.url),'utf8'));await db.exec('set role authenticated');assert.equal((await db.query('select cos_mhelp_intake.canary_v1() v')).rows[0].v,7);await db.query('select * from cos_mhelp_intake.canary');await assert.rejects(db.query('select * from cos_mhelp_intake.participants'),/permission denied/);await db.exec('reset role');});
test('only pristine canonical Service queue can bind prep and refresh its exact claim baseline',async()=>{await db.exec(`insert into public.job_assignments(id,ticket_no,created_from,assigned_role,assignment_scope,assigned_by,assigned_by_name) values('${id(15)}','SYN-42','mhelpdesk_service_intake','service','department','${id(9)}','Synthetic');select cos_mhelp_intake.register_assignment_v1('${id(100)}','${id(15)}','service',null);insert into public.prep_tickets values('${id(200)}','SYN-42','draft','Synthetic')`);await actor(db,1,'select cos_mhelp_intake.bind_prep_v1($1,$2,$3,$4)',[id(100),id(11),id(1),id(200)]);await actor(db,1,'select cos_mhelp_intake.bind_counterpart_queue_v1($1,$2,$3)',[id(100),id(15),id(200)]);assert.equal((await db.query('select to_jsonb(a)=b.baseline same from public.job_assignments a join cos_mhelp_intake.work_order_assignments b on b.assignment_id=a.id where a.id=$1',[id(15)])).rows[0].same,true);await db.exec(`update public.job_assignments set notes='Human edit' where id='${id(15)}'`);await assert.rejects(actor(db,1,'select cos_mhelp_intake.bind_counterpart_queue_v1($1,$2,$3)',[id(100),id(15),id(200)]),/not_pristine/);});
