import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {BATCH_CONTRACT,INTAKE_CONTRACT,IntakeFault,runMhelpIntake,sourceKey,validateBatch} from '../intake/mhelpIntakeRuntime.ts';
import {createBoundedMhelpSource,productionAdapterFor} from '../intake/mhelpIntakeSource.ts';
import {createLegacyIntakeHandler,createNativeIntakeSourceHandler,projectRunResult} from '../intake/mhelpIntakeHandlers.ts';
import {createExistingCredentialSourceRead,createExistingServiceRpc} from '../intake/mhelpIntakeTransport.ts';
const at='2026-10-10T12:05:00.000Z',now=()=>Date.parse(at),floor='2026-10-10T12:00:00.000Z';
const lease=()=>({state:'leased',leaseId:'10000000-0000-4000-8000-000000000001',portalId:'17',schemaContract:'synthetic-only',activationFloor:floor,createdAfter:'2026-10-10T11:59:59.999Z',createdBefore:at,leaseUntil:'2026-10-10T12:08:00.000Z'});
const policy=()=>({state:'ready',portalId:'17',activationFloor:floor,schemaContract:'synthetic-only',schemaEvidence:'Synthetic approved schema evidence',typeMappingsVerified:true,identityMappingsVerified:true,statusPoliciesVerified:true});
const ticket=(id=1)=>({contract:'cos-mhelp-legacy-intake-v1',schemaContract:'synthetic-only',source:{portalId:'17',ticketId:String(id),createdAt:'2026-10-10T12:01:00.000Z'}});
const batch=(tickets=[ticket()])=>({contract:BATCH_CONTRACT,portalId:'17',schemaContract:'synthetic-only',window:{createdAfter:lease().createdAfter,createdBefore:at},totalRows:tickets.length,partial:false,tickets});
const req=(body={action:'run'},url='https://synthetic.invalid/run')=>new Request(url,{method:'POST',headers:{'Content-Type':'application/json','x-camera-cron-secret':'synthetic-only'},body:JSON.stringify(body)});
function runtime(changes={}){
 const calls=[];const options={enabled:true,now,random:()=>0,readSource:async()=>batch(),sleep:async()=>{},rpc:async input=>{calls.push(structuredClone(input));if(input.action==='begin')return lease();if(input.action==='record')return {state:'created'};if(input.action==='finish')return {state:'complete',total:input.total,watermarkAdvanced:true};return {state:'backoff'};},...changes};return {calls,options};
}
test('disabled switch and inactive database states make no source reads or ticket writes',async()=>{
 const {calls,options}=runtime({enabled:false,readSource:async()=>{throw Error('not called')}});assert.equal((await runMhelpIntake(options)).state,'disabled');assert.equal(calls.length,0);
 for(const state of ['disabled','busy','backoff','idle']){const calls=[];const r=await runMhelpIntake({...options,enabled:true,rpc:async input=>{calls.push(input);return {state};}});assert.equal(r.state,state);assert.deepEqual(calls,[{action:'begin'}]);}
});
test('immutable source keys disambiguate portals and retain canonical ticket identity',()=>{
 assert.equal(sourceKey('17','42'),'["mhelpdesk","17","42"]');assert.notEqual(sourceKey('17','42'),sourceKey('174','2'));for(const id of ['','01','../42','42:17'])assert.throws(()=>sourceKey('17',id));
});
test('all durable outcomes precede watermark and source details never enter run summary',async()=>{
 const {calls,options}=runtime({readSource:async()=>batch([ticket(1),ticket(2),ticket(3)])});let n=0;const original=options.rpc;options.rpc=async input=>{const result=await original(input);return input.action==='record'?{state:['created','existing','review_needed'][n++],private:'synthetic-private'}:result;};
 const result=await runMhelpIntake(options);assert.deepEqual(result,{contract:INTAKE_CONTRACT,state:'complete',scanned:3,created:1,existing:1,reviewNeeded:1,watermarkAdvanced:true});assert.deepEqual(calls.map(c=>c.action),['begin','record','record','record','finish']);assert.deepEqual(calls.at(-1).expectedTicketIds,['1','2','3']);assert(!JSON.stringify(result).includes('synthetic-private'));
});
test('no watermark on lost write, unsupported receipt, malformed source or oversized batch',async()=>{
 for(const variant of ['write','disabled-receipt','source','limit']){
  const {calls,options}=runtime();const original=options.rpc;options.rpc=async input=>{if(input.action==='record'&&variant==='write')throw Error('private internal SQL');const result=await original(input);return input.action==='record'&&variant==='disabled-receipt'?{state:'disabled'}:result;};
  if(variant==='source')options.readSource=async()=>({...batch(),partial:true});if(variant==='limit')options.readSource=async()=>batch(Array.from({length:501},(_,i)=>ticket(i+1)));
  const result=await runMhelpIntake(options);assert.equal(result.state,'failed');assert.equal(result.watermarkAdvanced,false);assert(!calls.some(c=>c.action==='finish'));assert.equal(calls.at(-1).action,'fail');assert(!JSON.stringify(result).includes('private'));
 }
});
test('only safe transient failures retry with bounded exponential backoff and same source key',async()=>{
 const {calls,options}=runtime();let read=0,record=0;const sleeps=[],original=options.rpc;options.sleep=async ms=>sleeps.push(ms);options.readSource=async()=>{if(read++<1)throw new IntakeFault('SOURCE_UNAVAILABLE',true);return batch();};options.rpc=async input=>{if(input.action==='record'&&record++<2){calls.push(structuredClone(input));throw new IntakeFault('WRITE_UNAVAILABLE',true);}return original(input);};
 assert.equal((await runMhelpIntake(options)).state,'complete');assert.equal(read,2);assert.equal(record,3);assert.deepEqual(sleeps,[250,250,500]);const writes=calls.filter(c=>c.action==='record');assert(writes.every(c=>JSON.stringify(c)===JSON.stringify(writes[0])));
 const permanent=runtime({readSource:async()=>{throw new IntakeFault('SOURCE_INVALID');}});assert.equal((await runMhelpIntake(permanent.options)).code,'SOURCE_INVALID');assert(!permanent.calls.some(c=>c.action==='record'));
});
test('absolute deadline aborts even a transport that ignores its abort signal',async()=>{
 const {options,calls}=runtime({deadlineMs:20,readSource:async()=>new Promise(()=>{})});const before=Date.now();const r=await runMhelpIntake(options);assert.equal(r.code,'DEADLINE');assert(Date.now()-before<1000);assert(!calls.some(c=>c.action==='finish'));
});
test('strict scope and schema reject forged portal, history, invalid dates, duplicate keys and nested private fields',()=>{
 for(const mutate of [b=>b.portalId='18',b=>b.schemaContract='other',b=>b.tickets[0].source.createdAt='2026-10-10T11:59:59.999Z',b=>b.tickets[0].source.createdAt='2026-02-30T12:01:00Z',b=>b.tickets[0].source.createdAt=at,b=>b.tickets[0].source.contact={email:'private'},b=>b.tickets[0].request={billing:'private'},b=>b.tickets.push(ticket())]){const b=batch();mutate(b);assert.throws(()=>validateBatch(b,lease()));}
 const exactFloor=ticket();exactFloor.source.createdAt=floor;assert.equal(validateBatch(batch([exactFloor]),lease()).tickets.length,1);
});
function source(all,patch={}){const calls=[];const p=policy();const adapter={schemaContract:p.schemaContract,schemaEvidence:p.schemaEvidence,projectTicket:v=>v,readPage:async input=>{calls.push(input);return {totalRows:all.length,rows:all.slice(input.offset,input.offset+50)};},...patch};return {calls,read:createBoundedMhelpSource({getPolicy:async()=>p,adapterFor:()=>adapter,now})};}
test('source uses exact bounded 50-row pagination, stable order, 500 ticket ceiling and projection',async()=>{
 const {read,calls}=source(Array.from({length:500},(_,i)=>ticket(i+1)));const result=await read(batch().window,new AbortController().signal);assert.equal(result.totalRows,500);assert.equal(calls.length,10);assert.deepEqual(calls.map(c=>c.offset),[0,50,100,150,200,250,300,350,400,450]);assert(calls.every(c=>c.pageSize===50&&c.portalId==='17'));
 const huge=source(Array.from({length:501},(_,i)=>ticket(i+1)));await assert.rejects(huge.read(batch().window,new AbortController().signal),e=>e.code==='BATCH_LIMIT');assert.equal(huge.calls.length,1);
});
test('source rejects incomplete, repeated, out-of-order or changing-total pages before any intake',async()=>{
 const all=Array.from({length:51},(_,i)=>ticket(i+1));for(const type of ['short','repeat','order','total']){let count=0;const {read}=source(all,{readPage:async input=>{count++;if(type==='short')return {totalRows:51,rows:all.slice(0,49)};if(type==='order')return {totalRows:51,rows:all.slice(0,50).reverse()};return {totalRows:type==='total'&&count===2?52:51,rows:count===1?all.slice(0,50):[type==='repeat'?ticket(50):ticket(51)]};}});await assert.rejects(read(batch().window,new AbortController().signal));}
});
test('native policy checks independent activation floor, fixed portal and hard maximum interval',async()=>{
 for(const window of [{createdAfter:'2026-10-09T00:00:00.000Z',createdBefore:at},{createdAfter:at,createdBefore:at},{createdAfter:floor,createdBefore:'2026-10-10T12:31:00.000Z'}]){const {read,calls}=source([ticket()]);await assert.rejects(read(window,new AbortController().signal));assert.equal(calls.length,0);}
 const changed=source([{...ticket(),source:{...ticket().source,portalId:'18'}}]);await assert.rejects(changed.read(batch().window,new AbortController().signal));
});
test('no production schema adapter exists: policy flags alone can never activate intake',async()=>{
 assert.equal(productionAdapterFor(policy()),null);const read=createBoundedMhelpSource({getPolicy:async()=>policy(),adapterFor:productionAdapterFor,now});await assert.rejects(read(batch().window,new AbortController().signal),e=>e.code==='CONFIGURATION');
 for(const update of [{state:'disabled'},{typeMappingsVerified:false},{identityMappingsVerified:false},{statusPoliciesVerified:false},{schemaEvidence:''}]){let called=false;const r=createBoundedMhelpSource({getPolicy:async()=>({...policy(),...update}),adapterFor:()=>{called=true;return null;},now});await assert.rejects(r(batch().window,new AbortController().signal));assert.equal(called,false);}
});
test('legacy HTTP denies before body/config reads; request cannot select records, source, identity or settings',async()=>{
 let called=false;const denied=createLegacyIntakeHandler({authenticate:()=>false,run:async()=>{called=true;throw Error();}}),request=req();assert.equal((await denied(request)).status,403);assert.equal(request.bodyUsed,false);assert.equal(called,false);
 const h=createLegacyIntakeHandler({authenticate:()=>true,run:async()=>({...projectRunResult(await runMhelpIntake({enabled:false,rpc:async()=>{},readSource:async()=>{}})),ticket:'private'})});
 for(const body of [{action:'record',ticket:ticket()},{action:'run',portalId:'18'},{action:'run',actorId:'owner'},{action:'run',url:'https://other.invalid'},{action:'run',enabled:true},{action:'run',token:'private'},{action:'run',extra:'x'.repeat(300)}])assert.equal((await h(req(body))).status,400);
 const response=await h(req());assert.equal(response.status,200);assert(!(await response.text()).includes('private'));assert.equal((await h(req({action:'run'},'https://synthetic.invalid/run?url=bad'))).status,400);
});
test('native HTTP accepts only action and bounded date fields, and hides raw failure details',async()=>{
 let calls=0;const h=createNativeIntakeSourceHandler({authenticate:()=>true,read:async()=>{calls++;throw Error('private token/contact/raw vendor');}});
 for(const extra of [{portalId:'18'},{url:'https://other.invalid'},{ticket:ticket()},{actorId:'owner'},{action:'run'}])assert.equal((await h(req({action:'ticket_batch',...batch().window,...extra}))).status,400);
 const response=await h(req({action:'ticket_batch',...batch().window}));assert.equal(response.status,503);assert.equal(calls,1);assert(!(await response.text()).includes('private'));
});
test('runtime transport uses fixed source URL, current incoming credential, no service key and bounded response',async()=>{
 const calls=[];const read=createExistingCredentialSourceRead({projectUrl:'https://goqrnolcvqnirjmzaeyk.supabase.co',request:req(),fetch:async(url,init)=>{calls.push({url,init});return new Response(JSON.stringify(batch()));}});
 await read(batch().window,new AbortController().signal);assert.equal(calls[0].url,'https://tughscoxralhofrckvxy.supabase.co/functions/v1/cos-mhelp-ticket-source');assert.deepEqual(calls[0].init.headers,{'Content-Type':'application/json','x-camera-cron-secret':'synthetic-only'});assert.equal(calls[0].init.redirect,'error');assert.deepEqual(JSON.parse(calls[0].init.body),{action:'ticket_batch',...batch().window});
 assert.throws(()=>createExistingCredentialSourceRead({projectUrl:'https://other.invalid',request:req(),fetch}));
 for(const [status,retryable] of [[403,false],[429,true],[503,true]]){const r=createExistingCredentialSourceRead({projectUrl:'https://goqrnolcvqnirjmzaeyk.supabase.co',request:req(),fetch:async()=>new Response('private',{status})});await assert.rejects(r(batch().window,new AbortController().signal),e=>e.retryable===retryable&&!e.message.includes('private'));}
});
test('existing service client calls only single approved atomic RPC and safely classifies failures',async()=>{
 let seen;const rpc=createExistingServiceRpc({rpc:(name,args)=>({abortSignal:async signal=>{seen={name,args,signal};return {data:{state:'disabled'},error:null};}})});const signal=new AbortController().signal;assert.deepEqual(await rpc({action:'begin'},signal),{state:'disabled'});assert.deepEqual(seen,{name:'camera_mhelp_ticket_intake_v1',args:{p_request:{action:'begin'}},signal});
 const failed=createExistingServiceRpc({rpc:()=>({abortSignal:async()=>({data:null,error:{message:'private'},status:403})})});await assert.rejects(failed({action:'begin'},signal),e=>e.code==='WRITE_UNAVAILABLE'&&!e.retryable);
});

async function dbFixture(){const db=new PGlite();try{await db.exec(`create role anon;create role authenticated;create role service_role;create schema cos_mhelp_intake;create table cos_mhelp_intake.portal_config(portal_id text primary key,enabled boolean,activated_at timestamptz,schema_contract text,schema_evidence text);create table cos_mhelp_intake.receipts(portal_id text,ticket_id text,source_created_at timestamptz,state text,first_payload jsonb,primary key(portal_id,ticket_id));insert into cos_mhelp_intake.portal_config values('17',true,now()-interval '1 hour','synthetic-only','Synthetic schema evidence');`);await db.exec(await readFile(new URL('../intake/mhelp-intake-scheduler-proposal.sql',import.meta.url),'utf8'));return db;}catch(error){await db.close();throw error;}}
const begin=async db=>(await db.query('select cos_mhelp_intake.begin_intake_v1() v')).rows[0].v;
const state=async db=>(await db.query('select * from cos_mhelp_intake.scheduler_state')).rows[0];
const finish=async(db,id,ids=['1'],total=ids.length)=>(await db.query('select cos_mhelp_intake.finish_intake_v1($1,$2::jsonb,$3) v',[id,JSON.stringify(ids),total])).rows[0].v;
async function receipt(db,l,id='1'){await db.query("insert into cos_mhelp_intake.receipts values('17',$1,$2::timestamptz+interval '1 millisecond','review_needed','{\"schemaContract\":\"synthetic-only\"}')",[id,l.activationFloor]);}
test('scheduler SQL denies every public/service role helper and tables are RLS protected',async()=>{const db=await dbFixture();try{for(const role of ['anon','authenticated','service_role']){const r=(await db.query("select has_function_privilege($1,'cos_mhelp_intake.begin_intake_v1()','execute') f,has_table_privilege($1,'cos_mhelp_intake.scheduler_state','select') t",[role])).rows[0];assert.deepEqual(r,{f:false,t:false});}assert.equal((await db.query("select relrowsecurity r from pg_class where oid='cos_mhelp_intake.scheduler_state'::regclass")).rows[0].r,true);}finally{await db.close();}});
test('SQL begin is disabled-by-policy, single-portal, leased and bounded without caller-selected dates',async()=>{const db=await dbFixture();try{await db.exec('update cos_mhelp_intake.portal_config set enabled=false');assert.deepEqual(await begin(db),{state:'disabled'});await db.exec('update cos_mhelp_intake.portal_config set enabled=true');const l=await begin(db);assert.equal(l.state,'leased');assert.equal(Date.parse(l.createdAfter),Date.parse(l.activationFloor)-1);assert.equal(Date.parse(l.createdBefore)-Date.parse(l.activationFloor),900000);assert.deepEqual(await begin(db),{state:'busy'});await db.exec("insert into cos_mhelp_intake.portal_config values('18',true,now(),'v','e')");await assert.rejects(begin(db),/CONFIGURATION/);}finally{await db.close();}});
test('SQL finish never advances without complete unique durable receipt manifest; review is durable',async()=>{const db=await dbFixture();try{const l=await begin(db),before=(await state(db)).watermark;for(const [ids,total]of [[['1'],1],[['1','1'],2],[['1'],2],[[],1]])await assert.rejects(finish(db,l.leaseId,ids,total));assert.equal((await state(db)).watermark.getTime(),before.getTime());await receipt(db,l);const result=await finish(db,l.leaseId);assert.deepEqual(result,{state:'complete',total:1,watermarkAdvanced:true});assert.equal((await state(db)).watermark.toISOString(),l.createdBefore);assert.deepEqual(await finish(db,l.leaseId),result);await assert.rejects(finish(db,l.leaseId,['2']),/INCOMPLETE_BATCH/);}finally{await db.close();}});
test('SQL restart before watermark safely replays same window and stale lease cannot write or finish',async()=>{const db=await dbFixture();try{const first=await begin(db);await receipt(db,first);await db.exec("update cos_mhelp_intake.scheduler_state set lease_until=now()-interval '1 second'");const second=await begin(db);assert.notEqual(second.leaseId,first.leaseId);assert.equal(second.createdAfter,first.createdAfter);assert.equal(second.createdBefore,first.createdBefore);await assert.rejects(finish(db,first.leaseId),/LEASE_LOST/);assert.equal((await finish(db,second.leaseId)).state,'complete');const third=await begin(db);assert.equal(Date.parse(third.createdAfter),Date.parse(second.createdBefore)-600000);}finally{await db.close();}});
test('SQL disable or schema/floor changes fence an active run before writes/watermark',async()=>{for(const edit of ["enabled=false","schema_contract='changed'","activated_at=activated_at+interval '1 second'"]){const db=await dbFixture();try{const l=await begin(db);await receipt(db,l);await db.exec('update cos_mhelp_intake.portal_config set '+edit);await assert.rejects(finish(db,l.leaseId),/CONFIGURATION_CHANGED/);}finally{await db.close();}}});
test('SQL durable backoff uses only allowlisted codes and never advances on failures',async()=>{const db=await dbFixture();try{const l=await begin(db);await assert.rejects(db.query("select cos_mhelp_intake.fail_intake_v1($1,'private vendor body',true)",[l.leaseId]),/INVALID_FAILURE/);const r=(await db.query("select cos_mhelp_intake.fail_intake_v1($1,'SOURCE_UNAVAILABLE',true) v",[l.leaseId])).rows[0].v;assert.deepEqual(r,{state:'backoff',retryAfterSeconds:30});assert.deepEqual(await begin(db),{state:'backoff'});assert.equal((await state(db)).watermark.toISOString(),l.activationFloor);}finally{await db.close();}});
test('SQL empty complete scan can advance but historical/wrong-schema receipts cannot',async()=>{const db=await dbFixture();try{const l=await begin(db);await db.query("insert into cos_mhelp_intake.receipts values('17','1',$1::timestamptz-interval '1 second','created','{\"schemaContract\":\"synthetic-only\"}')",[l.activationFloor]);await assert.rejects(finish(db,l.leaseId),/MISSING_RECEIPTS/);assert.equal((await finish(db,l.leaseId,[],0)).total,0);}finally{await db.close();}});

import {createNativeMhelpTicketAccess} from '../intake/mhelpIntakeTokenAccess.ts';
import {nativeMhelpTokens} from '../../supabase/functions/cos-operations-pages/mhelpTokenRuntime.ts';
function tokenFixture({denied=false,contended=false,commitFailure=false}={}){
 const events=[];let stored='synthetic-expired',claims=0,commits=0;
 const envValues={SUPABASE_URL:'https://tughscoxralhofrckvxy.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'synthetic-native-only',COS_MHELP_CLIENT_ID:'synthetic-client',COS_MHELP_CLIENT_SECRET:'synthetic-client-secret',COS_MHELP_PORTAL_ID:'17'};
 const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}});
 const fetcher=async(url,init)=>{
  if(url.endsWith('/rest/v1/rpc/cos_mhelp_token_session')){const body=JSON.parse(init.body);events.push({kind:body.p_action,...body});if(body.p_action==='read')return json({configured:true,portal_id:'17',access_token:stored});if(body.p_action==='claim'){claims++;if(contended&&claims===1)return json({private:'synthetic'},409);return json({configured:true,portal_id:'17',lease_id:'40000000-0000-4000-8000-000000000001',refresh_token:'synthetic-stored-refresh'});}if(body.p_action==='commit'){stored=body.p_access_token;commits++;if(commitFailure&&commits===1)return json({},503);return json({committed:true});}if(body.p_action==='release')return json({released:true});throw Error('unexpected token operation');}
  if(url==='https://login.mhelpdesk.com/connect/token'){events.push({kind:'oauth'});return denied?json({private:'synthetic renewal rejected'},400):json({access_token:'synthetic-current',refresh_token:'synthetic-rotated',token_type:'Bearer',expires_in:3600});}
  if(url==='https://connect.mhelpdesk.com/api/v1.0/users/me'){events.push({kind:'account',renewed:init.headers.Authorization==='Bearer synthetic-current'});return init.headers.Authorization==='Bearer synthetic-expired'?json({private:'synthetic expired'},401):json({portalId:17});}
  if(url.startsWith('https://connect.mhelpdesk.com/api/v1.0/portal/17/Tickets?')){events.push({kind:'tickets',url});assert.equal(init.headers.Authorization,'Bearer synthetic-current');return json({totalRows:1,data:[ticket()]});}
  throw Error('Unexpected synthetic URL');
 };
 const env=name=>envValues[name],tokens=nativeMhelpTokens(env,fetcher),access=createNativeMhelpTicketAccess({env,fetch:fetcher,tokens});
 const makeSource=()=>{let client;const p=policy();return createBoundedMhelpSource({getPolicy:async()=>p,now,adapterFor:()=>({schemaContract:p.schemaContract,schemaEvidence:p.schemaEvidence,open:async(portal,signal)=>{client=await access.begin(portal,signal);},readPage:async input=>{const p=await client.readTicketPage(input);return {totalRows:p.totalRows,rows:p.data};},projectTicket:v=>v})});};
 return {events,makeSource,tokens};
}
test('intake expired account uses the SAME native token manager and persists rotated pair before bounded batch/write',async()=>{
 const f=tokenFixture({commitFailure:true}),{options,calls}=runtime({readSource:f.makeSource()});const result=await runMhelpIntake(options);assert.equal(result.state,'complete');assert.equal(f.events.filter(e=>e.kind==='oauth').length,1);const commits=f.events.filter(e=>e.kind==='commit');assert.equal(commits.length,2);assert.deepEqual(commits[0],commits[1]);assert(f.events.findIndex(e=>e.kind==='commit')<f.events.findIndex(e=>e.kind==='account'&&e.renewed));assert(f.events.findIndex(e=>e.kind==='account'&&e.renewed)<f.events.findIndex(e=>e.kind==='tickets'));assert.equal(calls.filter(c=>c.action==='record').length,1);const url=new URL(f.events.find(e=>e.kind==='tickets').url);assert.equal(url.searchParams.get('pageSize'),'50');assert.equal(url.searchParams.get('createStart'),lease().createdAfter);assert(!JSON.stringify(result).includes('synthetic'));
});
test('rejected renewal performs no ticket reads, no writer call and no watermark advance',async()=>{
 const f=tokenFixture({denied:true}),{options,calls}=runtime({readSource:f.makeSource()});const result=await runMhelpIntake(options);assert.equal(result.state,'failed');assert.equal(result.watermarkAdvanced,false);assert(!f.events.some(e=>e.kind==='tickets'));assert(!calls.some(c=>['record','finish'].includes(c.action)));assert.equal(f.events.filter(e=>e.kind==='oauth').length,3);assert(!JSON.stringify(result).includes('synthetic'));
});
test('rotation lease contention safely retries the existing manager and same durable intake lease',async()=>{
 const f=tokenFixture({contended:true}),{options,calls}=runtime({readSource:f.makeSource()});assert.equal((await runMhelpIntake(options)).state,'complete');assert.equal(f.events.filter(e=>e.kind==='claim').length,2);assert.equal(f.events.filter(e=>e.kind==='oauth').length,1);assert.equal(calls.filter(c=>c.action==='begin').length,1);assert.equal(calls.filter(c=>c.action==='record').length,1);
});
test('concurrent callers sharing nativeMhelpTokens retain single-flight rotation and bounded reads',async()=>{
 const f=tokenFixture();const results=await Promise.all([f.makeSource()(batch().window,new AbortController().signal),f.makeSource()(batch().window,new AbortController().signal)]);assert(results.every(r=>r.totalRows===1));assert.equal(f.events.filter(e=>e.kind==='oauth').length,1);assert.equal(f.events.filter(e=>e.kind==='commit').length,1);
});

import {createExistingCredentialPolicyRead} from '../intake/mhelpIntakeTransport.ts';
test('policy read uses existing legacy verifier action and transfers no project service key',async()=>{let seen;const read=createExistingCredentialPolicyRead({projectUrl:'https://tughscoxralhofrckvxy.supabase.co',request:req(),fetch:async(url,init)=>{seen={url,init};return new Response(JSON.stringify(policy()));}});assert.deepEqual(await read(new AbortController().signal),policy());assert.equal(seen.url,'https://goqrnolcvqnirjmzaeyk.supabase.co/functions/v1/camera-mhelp-readiness');assert.deepEqual(JSON.parse(seen.init.body),{action:'intake_policy'});assert.deepEqual(seen.init.headers,{'Content-Type':'application/json','x-camera-cron-secret':'synthetic-only'});});
test('uncertain finish acknowledgement is identified rather than claiming a confirmed unchanged watermark',async()=>{const {calls,options}=runtime();const original=options.rpc;options.rpc=async input=>{if(input.action==='finish')throw new IntakeFault('WRITE_UNAVAILABLE',true);return original(input);};const r=await runMhelpIntake(options);assert.equal(r.state,'failed');assert.equal(r.completionUncertain,true);assert.equal(projectRunResult(r).completionUncertain,true);assert.equal(calls.at(-1).action,'fail');});
test('native output rejects hidden nested objects even when its reader callback is faulty',async()=>{for(const mutate of [t=>t.request={site:{contact:'private'}},t=>t.source.assignment={state:'assigned',identities:[{contact:'private'}]},t=>t.ticketLead={sourceIdentity:'x',evidence:{private:'contact'}}]){const b=batch();mutate(b.tickets[0]);const h=createNativeIntakeSourceHandler({authenticate:()=>true,read:async()=>b});const r=await h(req({action:'ticket_batch',...b.window}));assert.equal(r.status,503);assert(!(await r.text()).includes('private'));}});
test('database lock conflict and serialization SQLSTATEs retry by the same stable receipt key',async()=>{for(const code of ['55P03','40P01','40001']){const failed=createExistingServiceRpc({rpc:()=>({abortSignal:async()=>({data:null,error:{code,message:'private SQL details'},status:409})})});await assert.rejects(failed({action:'record'},new AbortController().signal),e=>e.code==='WRITE_UNAVAILABLE'&&e.retryable&&!e.message.includes('private'));}});
test('native fail-closed schema/limit errors do not turn into transient retry loops',async()=>{for(const code of ['CONFIGURATION','SOURCE_INVALID','BATCH_LIMIT']){const read=createExistingCredentialSourceRead({projectUrl:'https://goqrnolcvqnirjmzaeyk.supabase.co',request:req(),fetch:async()=>new Response(JSON.stringify({code,error:'safe'}),{status:503})});await assert.rejects(read(batch().window,new AbortController().signal),e=>e.code===code&&!e.retryable);}});
import {projectIntakeReview,REVIEW_CONTRACT} from '../intake/mhelpIntakeReview.ts';
test('future Owner review DTO exposes only bounded printed ticket references, safe reason codes and aggregate health',()=>{const v={contract:REVIEW_CONTRACT,enabled:false,activationAt:null,pendingReviewCount:1,createdCount:0,lastAttemptAt:at,lastSuccessAt:null,failureCount:1,retryAfter:at,lastErrorCode:'SOURCE_INVALID',held:[{ticketNumber:'000042',reasonCodes:['source_status_review_required']}],heldTruncated:false};assert.deepEqual(projectIntakeReview(v),v);for(const patch of [{held:[{...v.held[0],sourceBody:{private:'data'}}]},{held:[{ticketNumber:'42',reasonCodes:['raw vendor body private']}]},{lastErrorCode:'private SQL message'},{pendingReviewCount:0},{held:Array(26).fill(v.held[0])},{actor:'owner'}])assert.throws(()=>projectIntakeReview({...v,...patch}));});
