import test from 'node:test';
import assert from 'node:assert/strict';
import {createPrivateEvidenceReader,PrivateEvidenceError,MAX_EVIDENCE_BYTES} from '../../supabase/functions/cos-operations-pages/privateEvidence.ts';
import {org,actor,role,doc,job,other,png,fixture} from './privateEvidenceFixtures.mjs';
async function denied(f,status=404,id=doc){await assert.rejects(f.reader(actor,id),error=>error instanceof PrivateEvidenceError&&error.statusCode===status);assert.equal(f.objects.length,0)}
test('authorized same-owner photo uses exact metadata only and returns no storage locator',async()=>{const f=fixture(),r=await f.reader(actor,doc);assert.deepEqual(r,{documentId:doc,contentType:'image/png',content:png.toString('base64'),byteLength:png.length});assert.equal(f.objects.length,1);assert.equal(f.calls.length,6);assert.ok(f.calls.every(p=>!p.includes(other)));assert.deepEqual(Object.keys(r).sort(),['byteLength','content','contentType','documentId']);});
for(const type of ['technician_signature','customer_signature'])test(type+' readable only in signatures bucket',async()=>{const f=fixture();f.state.documents[0].document_type=type;f.state.documents[0].storage_bucket='signatures';assert.equal((await f.reader(actor,doc)).contentType,'image/png');assert.equal(f.objects[0].bucket,'signatures')});
for(const table of ['user_profiles','roles','user_roles','role_permissions','documents','jobs']){
 test(table+' missing denies before any object',async()=>{const f=fixture({[table]:[]});await denied(f)});
 test(table+' duplicate denies before any object',async()=>{const f=fixture();f.state[table].push({...f.state[table][0]});await denied(f)});
 test(table+' malformed collection is503',async()=>{const f=fixture({[table]:{}});await denied(f,503)});
}
for(const [name,table,key,value,status] of [
 ['inactive','user_profiles','active',false,403],['wrong profile user','user_profiles','user_id',other,403],['wrong profile org','user_profiles','organization_id',other,403],['technician','user_profiles','department','service',403],
 ['role wrong org','roles','organization_id',other,403],['role not owner','roles','code','auditor',403],['role link wrong user','user_roles','user_id',other,403],['role link wrong role','user_roles','role_id',other,403],['revoked permission','role_permissions','permission_code','job.view_assigned',403],
 ['doc wrong id','documents','id',other,404],['doc wrong org','documents','organization_id',other,404],['doc has no job','documents','job_id',null,404],['job wrong id','jobs','id',other,404],['job wrong org','jobs','organization_id',other,404],['wrong bucket','documents','storage_bucket','documents',404],['non evidence type','documents','document_type','invoice',404],
 ['SVG','documents','content_type','image/svg+xml',415],['HTML','documents','content_type','text/html',415],['HEIC','documents','content_type','image/heic',415],
])test(name+' denied',async()=>{const f=fixture();f.state[table][0][key]=value;await denied(f,status)});
for(const path of [other+'/'+job+'/x.png',org+'/'+other+'/x.png',org+'/'+job+'/../x.png',org+'/'+job+'//x.png',org+'/'+job+'/%2e%2e/x.png',org+'/'+job+'/x.png?x=1',org+'/'+job+'/x.png#x','https://bad.invalid/x',org+'/'+job+'/x\\x.png',org+'/'+job+'/x\nx.png','/'+org+'/'+job+'/x.png',org+'/'+job+'/','.','a'.repeat(1025)])test('path rejects '+JSON.stringify(path.slice(0,100)),async()=>{const f=fixture();f.state.documents[0].storage_path=path;await denied(f)});
for(const id of ['',null,'not-uuid',doc+'/../'+other,doc+'?x=1'])test('invalid identifier '+id+' denies before reads',async()=>{const f=fixture();await denied(f,404,id);assert.equal(f.calls.length,0)});
test('fresh role permission checked again without storage after revoke',async()=>{const f=fixture();await f.reader(actor,doc);f.state.role_permissions=[];await assert.rejects(f.reader(actor,doc));assert.equal(f.objects.length,1)});
for(const [name,object,status] of [
 ['missing',()=>new Response('private path',{status:404}),404],['upstream400missing',()=>new Response('private path',{status:400}),404],['upstream credential error',()=>new Response('private-key',{status:403}),503],['redirect',()=>new Response(null,{status:302,headers:{location:'https://bad.invalid'}}),503],['server error',()=>new Response('private-key',{status:500}),503],['partial content',()=>new Response(png,{status:206}),503],['wrong MIME',()=>new Response(png,{headers:{'content-type':'image/jpeg'}}),415],['HTML mislabeled PNG',()=>new Response('<html>secret</html>',{headers:{'content-type':'image/png'}}),415],['empty',()=>new Response(null,{headers:{'content-type':'image/png'}}),503],['declared oversize',()=>new Response(png,{headers:{'content-type':'image/png','content-length':String(MAX_EVIDENCE_BYTES+1)}}),413],['stream oversize',()=>new Response(new Uint8Array(MAX_EVIDENCE_BYTES+1),{headers:{'content-type':'image/png'}}),413],['length mismatch',()=>new Response(png,{headers:{'content-type':'image/png','content-length':String(png.length+1)}}),503],['network exception',()=>{throw new Error('secret-key')},503],
])test(name+' safe error',async()=>{const f=fixture({object});await assert.rejects(f.reader(actor,doc),e=>e.statusCode===status&&!e.message.includes('private-key')&&!e.message.includes('secret-key'))});
test('cancels too-large stream instead of retaining entire file',async()=>{let cancelled=false;const stream=new ReadableStream({start(c){c.enqueue(new Uint8Array(MAX_EVIDENCE_BYTES+1))},cancel(){cancelled=true}});const f=fixture({object:()=>new Response(stream,{headers:{'content-type':'image/png'}})});await assert.rejects(f.reader(actor,doc),e=>e.statusCode===413);assert.equal(cancelled,true)});
test('exact maximum allowed with bounded JSON response',async()=>{const bytes=Buffer.alloc(MAX_EVIDENCE_BYTES);png.copy(bytes);const f=fixture({object:()=>new Response(bytes,{headers:{'content-type':'image/png','content-length':String(bytes.length)}})});const r=await f.reader(actor,doc);assert.equal(r.byteLength,MAX_EVIDENCE_BYTES);assert.ok(JSON.stringify(r).length<6*1024*1024)});
for(const [type,bytes] of [['image/jpeg',[255,216,255,0]],['image/webp',[82,73,70,70,0,0,0,0,87,69,66,80]],['image/gif',[71,73,70,56,57,97]]])test(type+' signature sniff',async()=>{const f=fixture({object:()=>new Response(new Uint8Array(bytes),{headers:{'content-type':type}})});f.state.documents[0].content_type=type;assert.equal((await f.reader(actor,doc)).contentType,type)});
test('GIF not supported for signatures',async()=>{const f=fixture();Object.assign(f.state.documents[0],{document_type:'technician_signature',storage_bucket:'signatures',content_type:'image/gif'});await denied(f,415)});
test('read error is sanitized',async()=>{const f=fixture({readError:true});await assert.rejects(f.reader(actor,doc),e=>e.statusCode===503&&!e.message.includes('private error'));assert.equal(f.objects.length,0)});
