import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('../../production-assignments-host.js',import.meta.url),'utf8');
const css=readFileSync(new URL('../../operations-host.css',import.meta.url),'utf8');
const origin=process.env.COS_TEST_ORIGIN||'http://127.0.0.1:4173';
const endpoint='https://tughscoxralhofrckvxy.supabase.co/functions/v1/cos-operations-pages';
const markup=`<div id="wlItHome"><main class="wl-it-command-workspace"><header class="wl-it-command-head"><h1>IT Dashboard</h1></header><label>Existing prep<input id="nativeValue" value="saved check"></label><p>Legacy check dashboard</p></main></div>`;
const host=`<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0;padding:16px;box-sizing:border-box;background:#071018;color:white;font-family:Arial}*{box-sizing:border-box}${css}</style><div id="appView">${markup}</div><div id="authView" class="hidden"></div><script>window.identity={id:'legacy-tech',role:'it',active:true};window.TechCheckContext={getRole:()=>identity.role,getEffectiveRole:()=>identity.role,getSession:()=>({user:{id:identity.id}}),getProfile:()=>({user_id:identity.id,active:identity.active}),db:{auth:{onAuthStateChange:fn=>{window.authChange=fn;return{}},getSession:async()=>({data:{session:{user:{id:identity.id},access_token:'synthetic-it-token'}}})}}};</script><script type="module" src="/landing-host.js"></script>`;
async function setup(page){const state={requests:[],assigned:true,fail:false,gate:null};await page.route('**/*',async route=>{const url=route.request().url();if(url===origin+'/landing-fixture')return route.fulfill({contentType:'text/html',body:host});if(url===origin+'/landing-host.js')return route.fulfill({contentType:'text/javascript',body:source});if(url.startsWith(origin+'/operations/dist/index.html'))return route.fulfill({status:307,headers:{location:'/?mode=production-assignments'}});if(url.startsWith(origin+'/'))return route.continue();if(url!==endpoint)return route.abort();const headers={'access-control-allow-origin':origin,'access-control-allow-methods':'POST, OPTIONS','access-control-allow-headers':'authorization, content-type'};if(route.request().method()==='OPTIONS')return route.fulfill({status:204,headers});const req=route.request().postDataJSON();state.requests.push(req);expect(req.method).toBe('GET');expect(await route.request().headerValue('authorization')).toBe('Bearer synthetic-it-token');if(state.gate)await state.gate;if(state.fail)return route.fulfill({status:503,headers,contentType:'application/json',body:JSON.stringify({error:'Assignment source unavailable'})});let data;if(req.path==='/api/tech/session')data={authorized:true,legacyTechnician:true,department:'it',name:'Fixture IT'};else if(req.path==='/api/tech/assignments')data={profile:{department:'it',display_name:'Fixture IT'},visits:state.assigned?[{visit_id:'11111111-1111-4111-8111-111111111111',department:'it',job_number:'FIX-501',customer_name:'Fixture customer',site_name:'Fixture site',visit_type:'IT_PREP',status:'scheduled',dispatch_status:'ready',scheduled_start:'2026-10-06T20:00:00Z'}]:[]};else if(req.path==='/api/tech/tasks')data={items:[]};else throw Error(req.path);return route.fulfill({status:200,headers,contentType:'application/json',body:JSON.stringify(data)});});await page.goto('/landing-fixture');const summary=page.getByRole('region',{name:'Operations assigned jobs',exact:true});await expect(summary.getByRole('button',{name:/FIX-501/})).toBeVisible();return {state,summary};}
test('IT landing shows native assigned prep directly and preserves existing check when opening queue',async({page})=>{const {state,summary}=await setup(page);await expect(summary).toContainText('ASSIGNED · NOT DISPATCHED');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);if(process.env.COS_SCREENSHOTS)await page.screenshot({path:process.env.COS_SCREENSHOTS+'/assigned-jobs-'+page.viewportSize().width+'.png',fullPage:true});await summary.getByRole('button',{name:/FIX-501/}).click();const frame=page.frameLocator('#cosProductionAssignmentsFrame');await expect(frame.getByRole('button',{name:/FIX-501/})).toBeVisible();await page.getByRole('button',{name:'Close Operations assignments'}).click();await expect(page.locator('#nativeValue')).toHaveValue('saved check');expect(state.requests.every(r=>r.method==='GET')).toBe(true);});
test('native refresh is honest on failure and clears revoked assignments',async({page})=>{const {state,summary}=await setup(page);state.fail=true;await summary.getByRole('button',{name:'Refresh',exact:true}).click();await expect(summary.getByRole('alert')).toContainText('Assignment source unavailable');await expect(summary.getByRole('button',{name:/FIX-501/})).toHaveCount(0);state.fail=false;state.assigned=false;await summary.getByRole('button',{name:'Refresh',exact:true}).click();await expect(summary).toContainText('No active Operations jobs assigned to you.');});
test('dashboard rebuild and focus reload native assignment list without duplicate panels',async({page})=>{const {state,summary}=await setup(page);await page.locator('#appView').evaluate((node,html)=>node.innerHTML=html,markup);await expect(summary).toHaveCount(1);await expect(summary.getByRole('button',{name:/FIX-501/})).toBeVisible();state.assigned=false;await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(summary).toContainText('No active Operations jobs assigned to you.');});
test('logout or identity change clears visible native data before a delayed response returns',async({page})=>{const {state,summary}=await setup(page);let release;state.gate=new Promise(done=>release=done);await summary.getByRole('button',{name:'Refresh',exact:true}).click();await page.evaluate(()=>window.authChange('SIGNED_OUT',null));await expect(summary).toHaveCount(0);release();await expect(page.getByRole('button',{name:/FIX-501/})).toHaveCount(0);await expect(page.locator('#nativeValue')).toHaveValue('saved check');});
test('owner preview never shows native technician assignment records',async({page})=>{const {summary}=await setup(page);await page.evaluate(()=>document.body.classList.add('owner-test-role-preview'));await expect(summary).toHaveCount(0);await expect(page.getByRole('button',{name:'Operations assignments',exact:true})).toBeHidden();});
