import {test,expect} from '@playwright/test';
import {mountRouterFixture} from './fixtures/routers.mjs';
const records=frame=>frame.getByLabel('Router records',{exact:true});
test('router overview, filtering, IP drilldown and stored map context remain read-only',async({page})=>{
 const {frame,state}=await mountRouterFixture(page);
 await expect(frame.getByLabel('InHand router overview')).toBeVisible();
 await expect(frame.locator('.router-metrics b')).toHaveText(['4','1','1','2']);
 await frame.getByRole('button',{name:'View routers & IPs',exact:true}).click();
 await expect(frame.getByRole('heading',{name:'Router inventory & reachability'})).toBeVisible();
 await expect(records(frame).getByRole('button')).toHaveCount(4);
 await frame.getByRole('textbox',{name:'Search routers'}).fill('192.0.2.3');
 await expect(records(frame).getByRole('button')).toHaveCount(1);
 await expect(frame.getByLabel('Selected router details')).toContainText('This name is duplicated');
 await expect(frame.getByRole('button',{name:'View same-name COS unit'})).toHaveCount(0);
 await frame.getByRole('textbox',{name:'Search routers'}).fill('');
 await frame.getByRole('combobox',{name:'Router status filter'}).selectOption('stale');
 await expect(records(frame).getByRole('button')).toHaveCount(1);
 await expect(records(frame)).toContainText('SS 039');
 await frame.getByRole('combobox',{name:'Router status filter'}).selectOption('reachable');
 await expect(frame.getByLabel('Selected router details')).toContainText('192.0.2.1/32');
 await expect(frame.getByLabel('Selected router details')).toContainText('Last recorded recovery');
 await frame.getByRole('button',{name:'View same-name COS unit'}).click();
 await expect(frame.getByLabel('Router context for selected unit')).toContainText('Same-name match only');
 await expect(frame.locator('.field-map-detail')).toContainText('Manual');
 await expect(frame.locator('.cos-field-pin')).toHaveCount(1);
 await expect(frame.getByLabel('Latitude',{exact:true})).toHaveValue('30');
 await expect(frame.locator('.router-map-note')).toContainText('Router GPS feed not connected');
 const size=await frame.locator('body').evaluate(()=>({width:innerWidth,content:document.documentElement.scrollWidth}));expect(size.content).toBeLessThanOrEqual(size.width);
 expect(state.requests.every(r=>r.method==='GET')).toBeTruthy();
 await frame.getByRole('button',{name:'View all InHand routers'}).click();
 await page.goBack();await expect(frame.getByLabel('COS field unit map')).toBeVisible();
});
test('missing GPS remains unpinned and source failure can retry without fabricating healthy fleet',async({page})=>{
 const {frame,state}=await mountRouterFixture(page,{fail:true,gps:false});
 await expect(frame.getByLabel('InHand router overview')).toContainText('Router fixture unavailable');
 await expect(frame.locator('.router-metrics b')).toHaveText(['—','—','—','—']);
 state.fail=false;await frame.getByRole('button',{name:'Refresh routers',exact:true}).click();
 await expect(frame.locator('.router-metrics b')).toHaveText(['4','1','1','2']);
 await frame.getByRole('button',{name:'Open location map'}).click();
 await expect(frame.getByLabel('Router context for selected unit')).toContainText('No router GPS');
 await expect(frame.locator('.cos-field-pin')).toHaveCount(0);
 await expect(frame.getByLabel('Latitude',{exact:true})).toHaveValue('');
 expect(state.requests.every(r=>r.method==='GET')).toBeTruthy();
});
test('refresh retains clearly marked old inventory on outage and clears it when authorization is denied',async({page})=>{
 const {frame,state}=await mountRouterFixture(page);
 await frame.getByRole('button',{name:'View routers & IPs',exact:true}).click();
 await expect(records(frame).getByRole('button')).toHaveCount(4);
 state.fail=true;await frame.getByRole('button',{name:'Refresh routers',exact:true}).click();
 await expect(frame.getByRole('alert')).toContainText('Showing the last successful inventory');
 await expect(records(frame).getByRole('button')).toHaveCount(4);
 state.fail=403;await frame.getByRole('button',{name:'Refresh routers',exact:true}).click();
 await expect(frame.getByRole('alert')).toContainText('Router fixture unavailable');
 await expect(records(frame)).toHaveCount(0);
 await expect(frame.getByText('192.0.2.1/32',{exact:true})).toHaveCount(0);
});
