import {test,expect} from '@playwright/test';
import {mountRouterFixture} from './fixtures/routers.mjs';
const records=frame=>frame.getByLabel('Router records',{exact:true});
const card=frame=>frame.locator('.company-health-card').filter({has:frame.getByRole('heading',{name:'InHand Routers',exact:true})});
async function openMap(frame){await frame.getByRole('button',{name:'More',exact:true}).click();await frame.getByRole('navigation',{name:'COS Operations',exact:true}).getByRole('button',{name:'Field Map',exact:true}).click();}
test('router overview, filtering, IP drilldown and stored map context remain read-only',async({page})=>{
 const {frame,state}=await mountRouterFixture(page);
 await expect(card(frame)).toBeVisible();
 await expect(card(frame)).toContainText('4 stored router records');
 await expect(card(frame)).toContainText('Live GPS setup pending');
 await frame.getByRole('button',{name:'Open router inventory',exact:true}).click();
 await expect(frame.getByRole('heading',{name:'Router inventory & reachability'})).toBeVisible();
 await expect(records(frame).getByRole('button')).toHaveCount(4);
 await frame.getByRole('textbox',{name:'Search routers'}).fill('192.0.2.3');
 await expect(records(frame).getByRole('button')).toHaveCount(1);
 await expect(frame.getByLabel('Selected router details')).toContainText('This name is duplicated');
 await expect(frame.getByRole('button',{name:'View same-name COS unit'})).toHaveCount(0);
 await frame.getByRole('textbox',{name:'Search routers'}).fill('');
 await frame.getByRole('combobox',{name:'Router status filter'}).selectOption('stale');
 await expect(records(frame).getByRole('button')).toHaveCount(1);
 await expect(records(frame)).toContainText('SS 039');
 await frame.getByRole('combobox',{name:'Router status filter'}).selectOption('reachable');
 await expect(frame.getByLabel('Selected router details')).toContainText('192.0.2.1/32');
 await expect(frame.getByLabel('Selected router details')).toContainText('Last recorded recovery');
 await frame.getByRole('button',{name:'View same-name COS unit'}).click();
 await expect(frame.getByLabel('Router context for selected unit')).toContainText('Same-name match only');
 await expect(frame.locator('.field-map-detail')).toContainText('Manual');
 await expect(frame.locator('.cos-field-pin')).toHaveCount(1);
 await expect(frame.getByLabel('Latitude',{exact:true})).toHaveValue('30');
 await expect(frame.locator('.router-map-note')).toContainText('Router GPS feed not connected');
 const size=await frame.locator('body').evaluate(()=>({width:innerWidth,content:document.documentElement.scrollWidth}));expect(size.content).toBeLessThanOrEqual(size.width);
 expect(state.requests.every(r=>r.method==='GET')).toBeTruthy();
 await frame.getByRole('button',{name:'View all InHand routers'}).click();
 await frame.locator('body').evaluate(()=>history.back());
 await expect(frame.getByLabel('COS field unit map')).toBeVisible();
 await frame.locator('body').evaluate(()=>history.forward());
 await expect(frame.getByRole('heading',{name:'Router inventory & reachability'})).toBeVisible();
});
test('missing GPS remains unpinned and source failure can retry without fabricating healthy fleet',async({page})=>{
 const {frame,state}=await mountRouterFixture(page,{fail:true,gps:false});
 await expect(card(frame)).toContainText('Router inventory could not be loaded.');
 await expect(card(frame)).toContainText('Router count unavailable');
 state.fail=false;await frame.getByRole('button',{name:'Retry dashboard',exact:true}).click();
 await expect(card(frame)).toContainText('4 stored router records');
 await openMap(frame);
 await expect(frame.getByLabel('Router context for selected unit')).toContainText('No router GPS');
 await expect(frame.locator('.cos-field-pin')).toHaveCount(0);
 await expect(frame.getByLabel('Latitude',{exact:true})).toHaveValue('');
 expect(state.requests.every(r=>r.method==='GET')).toBeTruthy();
});
test('refresh retains clearly marked old inventory on outage and clears it when authorization is denied',async({page})=>{
 const {frame,state}=await mountRouterFixture(page);
 await frame.getByRole('button',{name:'Open router inventory',exact:true}).click();
 await expect(records(frame).getByRole('button')).toHaveCount(4);
 state.fail=true;await frame.getByRole('button',{name:'Refresh routers',exact:true}).click();
 await expect(frame.getByRole('alert')).toContainText('Showing the last successful inventory');
 await expect(records(frame).getByRole('button')).toHaveCount(4);
 state.fail=403;await frame.getByRole('button',{name:'Refresh routers',exact:true}).click();
 await expect(frame.getByRole('alert')).toContainText('Router fixture unavailable');
 await expect(records(frame)).toHaveCount(0);
 await expect(frame.getByText('192.0.2.1/32',{exact:true})).toHaveCount(0);
});

test('router polling preserves an open map popup',async({page})=>{
 await page.clock.install({time:new Date()});
 const {frame,state}=await mountRouterFixture(page);
 await openMap(frame);
 await expect(frame.getByLabel('Router context for selected unit')).toContainText('Same-name match only');
 await frame.locator('.cos-field-pin-wrap').click();
 await expect(frame.locator('.leaflet-popup-content')).toContainText('Same-name router');
 const canvas=await frame.getByLabel('COS field unit map').boundingBox();
 await page.mouse.move(canvas.x+canvas.width/2,canvas.y+canvas.height/2);
 await page.mouse.down();await page.mouse.move(canvas.x+canvas.width/2+120,canvas.y+canvas.height/2,{steps:8});await page.mouse.up();
 await page.clock.runFor(1000);
 const transform=await frame.locator('.leaflet-map-pane').evaluate(el=>el.style.transform);
 const readsBefore=state.requests.filter(r=>r.path==='/api/routers').length;
 await page.clock.fastForward(61000);
 await expect.poll(()=>state.requests.filter(r=>r.path==='/api/routers').length).toBeGreaterThan(readsBefore);
 await expect(frame.locator('.leaflet-popup-content')).toContainText('Stored COS coordinates');
 expect(await frame.locator('.leaflet-map-pane').evaluate(el=>el.style.transform)).toBe(transform);
});
