import{test,before,after,beforeEach}from'node:test';import assert from'node:assert/strict';import{PGlite}from'@electric-sql/pglite';
import{setupDepartureFixture,start,id,actor}from'../legacy/tests/service-departure-fixture.mjs';
let db;before(async()=>{db=new PGlite();await db.exec('create role anon;create role authenticated;create role service_role bypassrls;');});after(async()=>db.close());beforeEach(async()=>setupDepartureFixture(db));
test('genuine own Start captures actual immutable gate IDs and never starts a coworker',async()=>{const before=(await db.query('select * from public.job_assignments where id=$1',[id(14)])).rows[0];const g=(await start(db)).rows[0].value;const saved=(await db.query('select * from cos_service_field.departure_starts')).rows[0];assert.equal(saved.inspection_id,id(303));assert.equal(saved.inventory_check_id,id(403));assert.equal(saved.actor_id,id(3));assert.equal(saved.readiness_snapshot.departure_ready,true);assert.deepEqual((await db.query('select started_at from public.job_assignments where id=$1',[id(13)])).rows[0].started_at,saved.started_at);assert.equal(g.id,saved.id);assert.deepEqual((await db.query('select * from public.job_assignments where id=$1',[id(14)])).rows[0],before);await assert.rejects(db.exec("update cos_service_field.departure_starts set started_at=now()"),/immutable/);});
test('same witness replays after inventory overwrites and never fabricates historical Start',async()=>{const first=(await start(db)).rows[0].value;await db.exec("update public.service_truck_inventory_checks set ready=false;update public.service_truck_stock set recon_battery_qty=0;");assert.deepEqual((await start(db)).rows[0].value,first);await db.exec(`update public.job_assignments set status='started',started_at=now() where id='${id(14)}'`);await assert.rejects(start(db,4),/historical Start cannot be adopted/);});
test('actual failed inspection, inventory and fake old completion markers deny without a witness or transition',async()=>{for(const mutation of["update public.morning_checks set truck_checks='{}'","update public.service_truck_inventory_checks set ready=false",`update public.job_assignments set completed_at=now() where id='${id(13)}'`]){await setupDepartureFixture(db);await db.exec(mutation);await assert.rejects(start(db));assert.equal((await db.query('select count(*)::int n from cos_service_field.departure_starts')).rows[0].n,0);assert.equal((await db.query('select status from public.job_assignments where id=$1',[id(13)])).rows[0].status,'assigned');}});
test('foreign, withdrawn and inactive identities lose future authority; generic private APIs remain denied',async()=>{await assert.rejects(actor(db,4,'select public.fixture_own_start($1,$2)',[id(13),id(200)]));await db.exec(`update public.profiles set active=false where user_id='${id(3)}'`);await assert.rejects(start(db));await db.exec(`update public.profiles set active=true where user_id='${id(3)}';update cos_mhelp_intake.participants set state='withdrawn',withdrawn_at=now() where assignment_id='${id(13)}'`);await assert.rejects(start(db));await db.exec('set role authenticated');await assert.rejects(db.exec('select * from cos_service_field.departure_starts'),/permission denied/);await db.exec('reset role');});
test('shared submission seal blocks only new Starts and leaves genuine prior witness replay intact',async()=>{const g=(await start(db)).rows[0].value;await db.exec(`insert into cos_service_field.job_submissions(work_order_id,installation_scope_revision,prep_ticket_id,membership_id,assignment_id,actor_id,departure_start_id,request_id,request_snapshot,completion_kind,current_scope_snapshot) select work_order_id,1,prep_ticket_id,membership_id,assignment_id,actor_id,id,'${id(900)}','{}','installation','{}' from cos_service_field.departure_starts;`);assert.equal((await start(db)).rows[0].value.id,g.id);await assert.rejects(start(db,4),/already submitted/);assert.equal((await db.query('select status from public.job_assignments where id=$1',[id(14)])).rows[0].status,'assigned');});

test('private component preserves unrelated existing schema and function privileges',async()=>{await setupDepartureFixture(db,{canary:true});await db.exec('set role authenticated');assert.equal((await db.query('select cos_service_field.unrelated_existing_capability() value')).rows[0].value,1);await assert.rejects(db.exec('select cos_service_field.capture_departure_start_v1(null,null)'),/permission denied/);await db.exec('reset role');});
