import test from 'node:test';import assert from 'node:assert/strict';
import {captureSourceReturnScope,logicalSession,canonicalJSON,sourceJournal,prepareSourceUploadIntent,uploadSourceEvidence,sourceReturnRPC,stageSourceReturn,PICKUP_SERVICE_CONFIRMATION} from '../../source-return-shared-v1.js';
const id=n=>`70000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const login=(actor=id(1),sid=id(2),iat=1)=>({user:{id:actor},access_token:'synthetic.'+Buffer.from(JSON.stringify({sub:actor,session_id:sid,iat})).toString('base64url')+'.signature'});
const defer=()=>{let resolve;const promise=new Promise(r=>resolve=r);return{promise,resolve};};
function fixture(){let session=login(),fresh=null,profile={user_id:id(1),role:'service',active:true},generation=0;const events=new Map(),calls=[],listeners=new Set();const view={isConnected:true,getClientRects:()=>view.hidden?[]:[{}],closest:()=>null};
 const win={location:{href:'https://synthetic.test/source'},addEventListener:(n,cb)=>events.set(n,cb),removeEventListener:(n)=>events.delete(n)};
 const db={auth:{getSession:async()=>({data:{session:fresh||session}}),onAuthStateChange:cb=>{listeners.add(cb);return{data:{subscription:{unsubscribe:()=>listeners.delete(cb)}}};}},rpc:async(name,args)=>{calls.push([name,args]);return{data:{state:'recorded'}};},storage:{from:()=>({upload:async(path,file,options)=>{calls.push(['upload',path,options]);return{};}})}};
 const app={db,getSession:()=>session,getProfile:()=>profile,getEffectiveRole:()=>profile.role,getEffectiveIdentity:()=>({id:session.user.id,role:profile.role,owner_test:false})};
 const scope=captureSourceReturnScope({context:()=>app,role:'service',view,isCurrent:()=>generation===0,window:win});
 const change=kind=>{if(kind==='actor')session=login(id(3));if(kind==='session')session=login(id(1),id(4));if(kind==='refresh')session=login(id(1),id(2),2);if(kind==='fresh-session')fresh=login(id(1),id(4));if(kind==='inactive')profile={...profile,active:false};if(kind==='hidden')view.hidden=true;if(kind==='detached')view.isConnected=false;if(kind==='generation')generation++;if(kind==='navigation')events.get('popstate')();};return{scope,db,calls,change,listeners,view};}
test('logical session binds actor/sub/session ID while allowing ordinary token refresh',()=>{assert.deepEqual(logicalSession(login()),{actor:id(1),session:id(2)});assert.equal(logicalSession({user:{id:id(3)},access_token:login().access_token}),null);const f=fixture();f.change('refresh');assert(f.scope.current());f.scope.dispose();assert.equal(f.listeners.size,0);});
for(const boundary of ['actor','session','fresh-session','inactive','hidden','detached','generation','navigation'])test(`fresh scope rejects ${boundary}`,async()=>{const f=fixture();f.change(boundary);await assert.rejects(()=>f.scope.assertFresh());f.scope.dispose();});
for(const boundary of ['actor','session','fresh-session','generation','navigation'])test(`late source RPC cannot publish after ${boundary}`,async()=>{const f=fixture(),gate=defer();f.db.rpc=()=>gate.promise;const run=sourceReturnRPC(f.scope,{assignmentId:id(5),returnId:id(6),request:{action:'record_return'},validate:()=>true});await new Promise(r=>setImmediate(r));f.change(boundary);gate.resolve({data:{state:'recorded'}});await assert.rejects(run);f.scope.dispose();});
test('journal original actor key and CAS prevent clearing newer work',()=>{const rows=new Map(),storage={getItem:k=>rows.get(k)??null,setItem:(k,v)=>rows.set(k,v),removeItem:k=>rows.delete(k)};const j=sourceJournal(storage,{actorId:id(1),assignmentId:id(5),returnId:id(6)});const first=j.save(null,{requestId:id(8)});j.save(first,{requestId:id(9)});assert.throws(()=>j.clear(first));assert.equal(j.parse().requestId,id(9));assert(!j.key.includes(id(2)));});
test('lost upload ack reuses exact immutable object path with no upsert',async()=>{const f=fixture(),file=new File(['synthetic photograph'],'stand.jpg',{type:'image/jpeg'});let saved;const input={returnId:id(6),files:[file],save:value=>{saved=value;}};const intent=await prepareSourceUploadIntent(f.scope,input);f.db.storage.from=()=>({upload:async(path,file,options)=>{f.calls.push([path,options]);return f.calls.length===1?{error:{message:'lost ack'}}:{error:{statusCode:409}};}});await assert.rejects(()=>uploadSourceEvidence(f.scope,{intent,files:[file]}));const retry=await prepareSourceUploadIntent(f.scope,{...input,existing:saved});await uploadSourceEvidence(f.scope,{intent:retry,files:[file]});assert.equal(f.calls[0][0],f.calls[1][0]);assert.equal(f.calls[1][1].upsert,false);f.scope.dispose();});
test('changed retry evidence is held instead of creating an orphan path',async()=>{const f=fixture(),file=new File(['A'],'a.jpg',{type:'image/jpeg'});const intent=await prepareSourceUploadIntent(f.scope,{returnId:id(6),files:[file],save(){}});await assert.rejects(()=>prepareSourceUploadIntent(f.scope,{returnId:id(6),files:[new File(['B'],'a.jpg',{type:'image/jpeg'})],existing:intent,save(){throw Error('must not save');}}));assert.equal(f.calls.length,0);f.scope.dispose();});
for(const boundary of ['actor','fresh-session','generation'])test(`Add Return remembered-unit result is discarded before save after ${boundary}`,async()=>{const f=fixture(),gate=defer(),effects=[];const run=stageSourceReturn(f.scope,{read:()=>gate.promise,save:draft=>effects.push(['save',draft]),publish:draft=>effects.push(['publish',draft])});await new Promise(r=>setImmediate(r));f.change(boundary);gate.resolve({ticket:'PRIVATE-SYNTHETIC'});await assert.rejects(run);assert.deepEqual(effects,[]);f.scope.dispose();});
test('staged success publishes explicitly without automatic Home navigation',async()=>{const f=fixture(),effects=[];await stageSourceReturn(f.scope,{read:async()=>({unit:null}),save:d=>effects.push(['save',d.unit]),publish:d=>effects.push(['publish',d.unit])});assert.deepEqual(effects,[['save',null],['publish',null]]);f.scope.dispose();});
test('Service confirmation explicitly sends set for assigned IT intake without claiming intake complete',()=>{assert.match(PICKUP_SERVICE_CONFIRMATION,/Send this set to the assigned IT team for intake/);assert.doesNotMatch(PICKUP_SERVICE_CONFIRMATION,/intake (finished|completed)/i);});
test('canonical requests retain NULL rather than coercing it to an empty tag',()=>{assert.notEqual(canonicalJSON({unitTag:null}),canonicalJSON({unitTag:''}));assert.equal(canonicalJSON({b:2,a:1}),canonicalJSON({a:1,b:2}));assert.throws(()=>canonicalJSON({a:undefined}));});

test('JWT fence rejects malformed segments, oversized tokens and actor/session ambiguity',()=>{for(const access_token of [login().access_token+'.extra','.'+login().access_token,login().access_token.replace('synthetic','bad header'), 'a'.repeat(17000)])assert.equal(logicalSession({user:{id:id(1)},access_token}),null);assert.equal(logicalSession(login(id(1),'not-uuid')),null);});
test('bounded JSON rejects depth, size, fanout and nonfinite values',()=>{let deep={};for(let i=0;i<18;i++)deep={next:deep};for(const value of [deep,{value:'x'.repeat(20001)},Array(10001).fill(1),Array(10).fill('x'.repeat(10000)),{value:NaN}])assert.throws(()=>canonicalJSON(value));});
test('upload rejects substituted bytes, invalid path and wrong intent metadata before storage',async()=>{for(const mutate of ['bytes','path','metadata']){const f=fixture(),file=new File(['A'],'a.jpg',{type:'image/jpeg'});const intent=await prepareSourceUploadIntent(f.scope,{returnId:id(6),files:[file],save(){}});let uploadFile=file;if(mutate==='bytes')uploadFile=new File(['B'],'a.jpg',{type:'image/jpeg'});if(mutate==='path')intent[0].path=intent[0].path.replace('/returns/','/elsewhere/');if(mutate==='metadata')intent[0].size++;await assert.rejects(()=>uploadSourceEvidence(f.scope,{intent,files:[uploadFile]}));assert.equal(f.calls.length,0);f.scope.dispose();}});
test('same-task hide/restore and detach/reinsert records permanently invalidate scope',()=>{for(const kind of ['style','class','hidden','aria-hidden','removed']){let callback;const session=login(),view={isConnected:true,getClientRects:()=>[{}],closest:()=>null},win={location:{href:'synthetic'},addEventListener(){},removeEventListener(){},MutationObserver:class{constructor(fn){callback=fn;}observe(){}disconnect(){}}};const c={db:{auth:{onAuthStateChange(){}}},getSession:()=>session,getProfile:()=>({user_id:id(1),role:'service',active:true}),getEffectiveIdentity:()=>({id:id(1),role:'service'})};const scope=captureSourceReturnScope({context:()=>c,role:'service',view,window:win,document:{documentElement:{},addEventListener(){},removeEventListener(){}}});callback([kind==='removed'?{type:'childList',removedNodes:[view]}:{type:'attributes',target:view,attributeName:kind,oldValue:{style:'display:none',class:'hidden',hidden:'', 'aria-hidden':'true'}[kind]}]);assert.equal(scope.current(),false);scope.dispose();}});
