import {test,expect} from '@playwright/test';
import {snapshot as cameraSnapshot} from './fixtures/camera-evidence-fixtures.mjs';
import {sourceRecordedFixture,now} from './fixtures/source-recorded-coordinates-fixture.mjs';
const origin=process.env.COS_MAP_TEST_ORIGIN||'http://127.0.0.1:4173';
test('tracker literal coordinates show blue SRC support pin, provenance and stale-address removal',async({page},info)=>{
 const f=await sourceRecordedFixture(),state={rows:[f.row],writes:[]};await page.clock.install({time:new Date(now)});
 await page.route('**/*',async route=>{
  const url=route.request().url();if(url===origin+'/source-recorded-fixture')return route.fulfill({contentType:'text/html',body:`<meta name="viewport" content="width=device-width,initial-scale=1"><style>html,body{margin:0;height:100%}iframe{width:100%;height:100%;border:0}</style><iframe src="/#field-map"></iframe><script>addEventListener('message',e=>{if(e.origin===location.origin&&e.data.type==='COS_OPERATIONS_TOKEN_REQUEST')e.source.postMessage({type:'COS_OPERATIONS_TOKEN_RESPONSE',requestId:e.data.requestId,role:'owner',accessToken:'synthetic-only'},location.origin)})</script>`});
  if(url.startsWith(origin+'/'))return route.continue();if(/^https:\/\/[abc]\.tile\.openstreetmap\.org\//.test(url))return route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="256" height="256"><rect width="256" height="256" fill="#34495b"/></svg>'});
  if(!url.endsWith('/functions/v1/cos-operations-pages'))return route.abort('blockedbyclient');
  const headers={'access-control-allow-origin':origin,'access-control-allow-methods':'POST, OPTIONS','access-control-allow-headers':'authorization, content-type'};if(route.request().method()==='OPTIONS')return route.fulfill({status:204,headers});
  const request=route.request().postDataJSON();if(request.method!=='GET'){state.writes.push(request);return route.fulfill({status:400,headers,body:'{}'});}
  const data=request.path==='/api/session'?{authorized:true,name:'Synthetic Owner',role:'Owner',features:{fieldLocationVerification:true}}:request.path==='/api/field-map'?{...f.snapshot,items:state.rows,inventoryItems:state.rows,generatedAt:new Date(now).toISOString()}:request.path==='/api/camera-health/summary-v3'?cameraSnapshot([]):request.path==='/api/routers'?{items:[],source:'camera_health',gpsAvailable:false,generatedAt:new Date(now).toISOString()}:request.path==='/api/equipment'?{items:[],models:[],trackerUnits:state.rows}:request.path==='/api/daily-board'?{jobs:[],tasks:[],readiness:[],asOf:new Date(now).toISOString()}:{items:[]};return route.fulfill({headers,contentType:'application/json',body:JSON.stringify(data)});
 });
 await page.goto('/source-recorded-fixture');const frame=page.frameLocator('iframe');await expect(frame.locator('.cos-field-pin-recorded[data-health="support"]')).toHaveCount(1);await expect(frame.locator('.cos-field-pin-recorded .cos-pin-location-tag')).toHaveText('SRC');await expect(frame.locator('.cos-field-pin-recorded .cos-pin-location-tag')).toHaveCSS('top','44px');
 await frame.locator('.field-map-center').scrollIntoViewIfNeeded();await frame.locator('.field-map-center').screenshot({path:info.outputPath('source-recorded-blue-stand.png')});
 await frame.locator('.field-map-list>button').click();await expect(frame.locator('.field-map-detail')).toContainText('0 CAMERAS');await expect(frame.locator('.field-map-detail')).toContainText('SOURCE RECORDED');await expect(frame.getByRole('region',{name:'Tracker-recorded coordinates'})).toContainText('measurement time is unknown');await expect(frame.getByRole('region',{name:'Tracker-recorded coordinates'})).toContainText('tracker cell N19');await expect(frame.locator('.field-map-detail')).toContainText('Last unit GPSNot recorded');
 await expect(frame.getByLabel('Nearby unit center').locator('option[value="'+f.row.id+'"]')).toHaveCount(0);await expect(frame.locator('.field-map-kpis article').nth(1).locator('b')).toHaveText('0');await expect(frame.getByRole('button',{name:'Save verified location',exact:true})).toHaveCount(0);
 await page.reload();await expect(frame.locator('.cos-field-pin-recorded')).toHaveCount(1);
 state.rows=[{...f.row,address:'Different Rd, Test City, TX 77001'}];await frame.getByRole('button',{name:'Refresh',exact:true}).click();await expect(frame.locator('.cos-field-pin-recorded')).toHaveCount(0);await expect(frame.getByRole('region',{name:'Tracker-recorded coordinates'})).toHaveCount(0);expect(state.writes).toHaveLength(0);
});
