import{test}from'node:test';import assert from'node:assert/strict';import{mkdtemp,writeFile,readFile,rm,mkdir}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';
import{statements,build,plan}from'../scripts/build-support-admission.mjs';import{record,productRecord,review}from'./fixtures/support-admission-fixture.mjs';
import {creationIdentity} from '../scripts/product-creation-identity.mjs';
test('preparation emits bounded transactions and SQL-escapes data without executing it',()=>{const files=statements([record({customer:"O'Example"})],review());assert.match(files['dry-run.sql'],/O''Example/);assert.match(files['dry-run.sql'],/false\);\nrollback;/);assert.match(files['execute.sql'],/true\);\ncommit;/);assert.match(files['execute.sql'],/read committed/);assert.equal(files['withdraw.sql'],undefined);});
test('withdrawal generation requires complete matching successful execution identities',()=>{const row=record(),receipt={applied:true,records:[{productId:row.productId,trackerId:'00000000-0000-4000-8000-000000000001',sourceRevision:'00000000-0000-4000-8000-000000000002',status:'admitted'}]};assert.match(statements([row],review(),receipt)['withdraw.sql'],/cos_support_withdraw_reviewed/);for(const changed of[{...receipt,applied:false},{...receipt,records:[]},{...receipt,records:[{...receipt.records[0],productId:'999'}]}])assert.throws(()=>statements([row],review(),changed));});
test('payloads and output stay outside the repository and existing artifacts are never overwritten',async()=>{const dir=await mkdtemp(join(tmpdir(),'support-builder-'));try{await writeFile(join(dir,'records.json'),JSON.stringify([record()]));await writeFile(join(dir,'review.json'),JSON.stringify(review()));const inputs={recordsPath:join(dir,'records.json'),reviewPath:join(dir,'review.json'),outPath:join(dir,'output')};const manifest=await build(inputs);assert.equal(manifest.productionWrites,0);assert.equal(manifest.recordCount,1);assert.match(await readFile(join(dir,'output/execute.sql'),'utf8'),/cos_support_admit_reviewed/);await assert.rejects(()=>build(inputs),/EEXIST/);await assert.rejects(()=>build({...inputs,recordsPath:new URL('../package.json',import.meta.url).pathname}),/outside/);}finally{await rm(dir,{recursive:true,force:true});}});
test('typed preparation keeps family discriminators and rejects unsupported suffix/capacity tokens',()=>{
 for(const kind of ['wall_e','camv','sniper_2']){const row=productRecord(kind);const files=statements([row],review());assert.ok(files['execute.sql'].includes(row.sourceLabel));assert.match(creationIdentity(row).identityKey,/901$/);for(const change of [{capacity:72},{sourceLabel:row.sourceLabel+' HD4'},{variant:'HD4'},{number:'0901'},{kind:'constructor'},{productId:'9223372036854775808'}])assert.throws(()=>statements([{...row,...change}],review()));}
 assert.equal(creationIdentity(productRecord('sniper_2')).unitNumber,'Sniper 2 901');
 assert.equal(creationIdentity(record({kind:'solar_pole',sourceCategory:'Solar Pole 72',capacity:72,sourceLabel:'Solar Pole 901 72 (Hybrid solar stand)'})).identityKey,'Solar Pole 72|901');
 assert.throws(()=>statements([productRecord(),productRecord('wall_e',{productId:'9000099'})],review()));
});
test('private apply-plan stores source observations without fabricating fresh review or execution SQL',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'product-plan-'));try{
  const records=['wall_e','camv','sniper_2'].map(kind=>productRecord(kind));const recordsPath=join(dir,'records.json'),outPath=join(dir,'output');await writeFile(recordsPath,JSON.stringify(records));
  const result=await plan({recordsPath,outPath});assert.equal(result.status,'awaiting_fresh_independent_review');assert.deepEqual(result.records,records);assert.equal(result.reviewReceipt,null);assert.equal(result.productionWrites,0);assert.equal(result.providerCalls,0);assert.equal(result.reviewedAt,undefined);assert.equal(result.recordCount,3);assert.ok(result.proposedTargets.every(r=>r.trackerId===null&&r.cameraCount===null&&r.cameraHealth==='unknown'&&!r.providerAssociation));
  assert.deepEqual(JSON.parse(await readFile(join(outPath,'apply-plan.json'),'utf8')),result);await assert.rejects(()=>readFile(join(outPath,'execute.sql')),/ENOENT/);await assert.rejects(()=>plan({recordsPath,outPath}),/EEXIST/);
 }finally{await rm(dir,{recursive:true,force:true});}
});
