import {test,expect} from '@playwright/test';
import {existsSync} from 'node:fs';
import {resolve,extname} from 'node:path';
import {fileURLToPath} from 'node:url';
const origin=process.env.COS_TRACKER_TEST_ORIGIN||'http://127.0.0.1:4173',dist=resolve(process.env.COS_TRACKER_TEST_DIST||fileURLToPath(new URL('../dist',import.meta.url)));
const workbook='1eV9dx7z1deyA5w9iaVNpP0D5_otkfF-dLiC5wuAlbtA',id='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222',revision='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',stamp='2026-10-09T04:00:00Z';
const source=()=>({unitId:id,sourceRevision:revision,pendingRequestId:null,sourceIdentity:{sourceSystem:'google_sheet_tracker',sourceRecordId:'google_sheet:'+workbook+':10:Solar Pole 72|003'},family:'SOLAR POLES & SKIDS',fullVariant:'Solar Pole 72',unitLabel:'003',fields:{placement:'FIELD',street:'100 Example Road',city:'Houston',state:'TX',zip:null,siteLabel:'Source yard',customerLabel:'Example Customer'}});
async function mount(page,{role='owner',queue=true,feature=true,unavailable=false,home=false,address=false,holdRead=false}={}){
 const s=source(),state={writes:[],reads:[],requests:[],failPost:false,badReceipt:false,badReadback:false,mismatchReceipt:false,wrongActor:false,truncated:false,held:false,failRead:false,holdRead,errors:[],source:s};let release;const held=new Promise(r=>release=r);state.release=release;let releaseRead;const readHeld=new Promise(r=>releaseRead=r);state.releaseRead=releaseRead;
 const data=()=>({contract:'COS_UNIT_TRACKER_OUTBOX_V1',workbookId:workbook,connector:{enabled:false,state:'awaiting_sheets_connection'},queueEnabled:queue&&!unavailable,availability:unavailable?'unavailable':'available',sources:unavailable?[]:[s],requests:state.truncated?[]:state.requests,sourcesTruncated:false,requestsTruncated:state.truncated,sourcesHeld:0});
 const inventory=[{id,unitNumber:'Solar Pole 72 003',modelName:'Solar Pole 72',readOnly:true,status:'field',currentLocationType:'FIELD',site:'Current Owner yard',customer:'Example Customer',address:'200 New Road, Houston, TX 77001',hasUnitGps:false},{id:other,unitNumber:'Solar Pole 72 003',modelName:'Different registered record',readOnly:false,status:'shop',currentLocationType:'SHOP'}];
 page.on('pageerror',error=>state.errors.push(error.message));
 await page.route('**/*',async route=>{
  const url=route.request().url();
  if(url===origin+'/tracker-fixture')return route.fulfill({contentType:'text/html',body:`<meta name="viewport" content="width=device-width,initial-scale=1"><style>html,body{margin:0;height:100%}iframe{width:100%;height:100%;border:0}</style><iframe src="/${role==='owner'?'':'?mode=fleet'}#${home?'today':'unit-tracker'}"></iframe><script>addEventListener('message',e=>{if(e.origin===location.origin&&e.data.type==='COS_OPERATIONS_TOKEN_REQUEST')e.source.postMessage({type:'COS_OPERATIONS_TOKEN_RESPONSE',requestId:e.data.requestId,role:${JSON.stringify(role)},accessToken:'synthetic-only'},location.origin)})</script>`});
  if(url.startsWith(origin+'/')){const pathname=new URL(url).pathname,path=resolve(dist,pathname==='/'?'index.html':'.'+decodeURIComponent(pathname));if(path.startsWith(dist+'/')&&existsSync(path))return route.fulfill({path,contentType:{'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.woff':'font/woff'}[extname(path)]||'application/octet-stream'});return route.abort();}
  if(!url.endsWith('/functions/v1/cos-operations-pages'))return route.abort('blockedbyclient');
  const headers={'access-control-allow-origin':origin,'access-control-allow-methods':'POST, OPTIONS','access-control-allow-headers':'authorization, content-type'};
  if(route.request().method()==='OPTIONS')return route.fulfill({status:204,headers});
  const request=route.request().postDataJSON(),answer=(data,status=200)=>route.fulfill({status,headers,contentType:'application/json',body:JSON.stringify(data)});
  if(request.method==='POST'){
   state.writes.push(request);if(state.held)await held;if(state.failPost)return answer({error:'The current tracker source changed. Reload before saving.'},409);
   if(request.path!=='/api/unit-tracker/requests')return answer({error:'No production changes in fixtures.'},403);
   const p=request.body,before=p.kind==='add'?null:s.fields,identity=p.kind==='add'?{...p.identity,unitId:null,sourceRecordId:null}:{family:s.family,fullVariant:s.fullVariant,unitLabel:s.unitLabel,unitId:id,sourceRecordId:s.sourceIdentity.sourceRecordId};
   const record={requestId:p.requestId,kind:p.kind,status:'awaiting_sheets_connection',createdAt:stamp,identity,expectedSourceRevision:p.kind==='add'?null:p.expectedSourceRevision,changes:p.changes,before,proposed:{placement:null,street:null,city:null,state:null,zip:null,siteLabel:null,customerLabel:null,...before,...p.changes}};
   if(state.mismatchReceipt)record.changes={...record.changes,siteLabel:'Mismatched yard'};state.requests.unshift(record);if(p.kind==='update')s.pendingRequestId=p.requestId;return answer(state.badReceipt?{}:{created:true,ownedByCurrentActor:!state.wrongActor,request:record,connector:data().connector});
  }
  state.reads.push(request.path);
  if(request.path==='/api/session')return answer({authorized:true,legacyOwner:role==='owner',role:role==='owner'?'Owner':'IT',name:'Synthetic '+role,features:{fleetAccess:true,unitTracker:feature,importedUnitAddressEdit:address}});
  if(request.path==='/api/field-map')return answer({items:[inventory[0]],inventoryItems:inventory,summary:{fieldUnits:1,mappedUnits:0,unitGps:0,missingGps:1},generatedAt:stamp});
  if(request.path==='/api/unit-tracker'){if(state.holdRead)await readHeld;if(state.failRead)return answer({error:'Tracker read unavailable.'},503);return answer(data());}
  if(request.path.startsWith('/api/unit-tracker/requests/')){const found=state.badReadback?null:state.requests.find(row=>row.requestId===request.path.split('/').at(-1))||null;return answer({request:found,ownedByCurrentActor:Boolean(found)&&!state.wrongActor,connector:data().connector});}
  if(request.path==='/api/unit-tracker/'+id)return answer({...s,queueEnabled:queue,connector:data().connector,pendingRequest:state.requests.find(row=>row.requestId===s.pendingRequestId)||null});
  if(request.path==='/api/field-map/'+id+'/address')return answer({contract:'COS_APP_UNIT_ADDRESS_V1',unitId:id,unitNumber:'Solar Pole 72 003',sourceIdentity:s.sourceIdentity,sourceRevision:revision,revision:null,placementRevision:'a'.repeat(64),placement:'FIELD',installation:{street:'200 New Road',city:'Houston',state:'TX',zip:'77001'},siteLabel:'Current Owner yard',sourceConflict:false,history:[],editable:true});
  return answer({items:[]});
 });
 await page.goto('/tracker-fixture');const frame=page.frameLocator('iframe');
 if(role!=='service'&&feature&&!home)await expect(frame.getByRole('region',{name:'Unit Tracker workspace',exact:true})).toBeVisible();
 return {frame,state,workspace:frame.getByRole('region',{name:'Unit Tracker workspace',exact:true})};
}
async function add(workspace){await workspace.getByRole('button',{name:'+ Add unit request',exact:true}).click();const form=workspace.getByRole('region',{name:'Add unit request',exact:true});await form.getByLabel('Family',{exact:true}).fill('SOLAR POLES & SKIDS');await form.getByLabel('Full model / variant',{exact:true}).fill('Solar Pole 72');await form.getByLabel('Unit label',{exact:true}).fill('004');return form;}
async function confirm(form){await form.getByRole('checkbox',{name:/I reviewed this exact unit/}).check();await form.getByRole('button',{name:'Save pending request',exact:true}).click();}
for(const role of ['owner','it'])test(role+' can browse full unit identities and save a durable pending addition with truthful status',async({page},info)=>{
 const {workspace,state}=await mount(page,{role});await expect(workspace.locator('tbody tr')).toHaveCount(2);await expect(workspace).toContainText('Sheets connection required');const form=await add(workspace);await expect(form.getByRole('button',{name:'Save pending request',exact:true})).toBeDisabled();await confirm(form);await expect(workspace).toContainText('Request saved in COS and verified');const pending=workspace.getByRole('region',{name:'Saved pending tracker requests'});await expect(pending).toContainText('Solar Pole 72 004');await pending.locator('summary').click();await expect(pending).toContainText('not been sent to Google Sheets or applied to fleet records');expect(state.writes).toHaveLength(1);expect(state.writes[0].body.kind).toBe('add');expect(state.writes[0].body.changes).toEqual({placement:'SHOP'});expect(state.writes[0].body.unitId).toBeUndefined();expect(state.errors).toEqual([]);const widths=await workspace.evaluate(e=>({scroll:e.scrollWidth,width:e.clientWidth}));expect(widths.scroll).toBeLessThanOrEqual(widths.width+1);await workspace.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:info.outputPath('unit-tracker-'+role+'.png')});
});
test('update prefill uses exact tracker row, displays newer COS data separately and preserves untouched blanks',async({page})=>{
 const {workspace,state}=await mount(page,{address:true});await workspace.getByRole('button',{name:'Solar Pole 72 003',exact:true}).first().click();const detail=workspace.getByRole('region',{name:'Unit Tracker details',exact:true});await expect(detail).toContainText('200 New Road');await expect(detail).toContainText('100 Example Road');await detail.getByRole('button',{name:'Request tracker change',exact:true}).click();const form=workspace.getByRole('region',{name:'Edit tracker request',exact:true});await expect(form.getByLabel('Street',{exact:true})).toHaveValue('100 Example Road');await expect(form.getByLabel('ZIP',{exact:true})).toHaveValue('');await form.getByLabel('Site label',{exact:true}).fill('');await confirm(form);await expect(workspace).toContainText('Request saved in COS and verified');expect(state.writes).toHaveLength(1);expect(state.writes[0].body).toMatchObject({kind:'update',unitId:id,expectedSourceRevision:revision,changes:{siteLabel:null}});expect(Object.keys(state.writes[0].body.changes)).toEqual(['siteLabel']);expect(state.source.fields.street).toBe('100 Example Road');expect(state.source.fields.siteLabel).toBe('Source yard');
});
test('disabled or absent outbox never offers a save or claims queued data',async({page})=>{const {workspace,state}=await mount(page,{unavailable:true});await expect(workspace.getByRole('button',{name:'+ Add unit request'})).toBeDisabled();await expect(workspace).toContainText('not enabled on this backend');await expect(workspace.locator('tbody tr')).toHaveCount(2);expect(state.writes).toEqual([]);});
test('Service receives no Unit Tracker workspace or writes',async({page})=>{const {frame,state}=await mount(page,{role:'service'});await expect(frame.getByText('ACCESS UNAVAILABLE',{exact:true})).toBeVisible();await expect(frame.getByRole('region',{name:'Unit Tracker workspace'})).toHaveCount(0);expect(state.writes).toEqual([]);expect(state.reads).toEqual([]);});
test('old backend capability omits Owner home entry',async({page})=>{const {frame,state}=await mount(page,{feature:false,home:true});await expect(frame.getByText('OPERATIONS CONNECTED',{exact:true})).toBeVisible();await expect(frame.getByRole('region',{name:'Home Unit Tracker'})).toHaveCount(0);expect(state.reads.includes('/api/unit-tracker')).toBe(false);});
test('Owner has direct Home entry and Back restores the dashboard',async({page})=>{const {frame}=await mount(page,{home:true});await frame.getByRole('region',{name:'Home Unit Tracker'}).getByRole('button',{name:'Open Unit Tracker'}).click();await expect(frame.getByRole('region',{name:'Unit Tracker workspace'})).toBeVisible();await frame.locator('body').evaluate(()=>history.back());await expect(frame.getByRole('region',{name:'Home Unit Tracker'})).toBeVisible();});
test('cancel and Escape discard unsaved additions without submitting',async({page})=>{const {workspace,state}=await mount(page);let form=await add(workspace);await form.getByRole('button',{name:'Cancel request edits'}).click();await expect(form).toHaveCount(0);form=await add(workspace);await form.getByLabel('Unit label',{exact:true}).press('Escape');await expect(form).toHaveCount(0);expect(state.writes).toEqual([]);});
test('repeated save clicks create one request while the response is pending',async({page})=>{const {workspace,state}=await mount(page);const form=await add(workspace);state.held=true;await form.getByRole('checkbox').check();await form.getByRole('button',{name:'Save pending request'}).dblclick();await expect.poll(()=>state.writes.length).toBe(1);state.release();await expect(workspace).toContainText('Request saved in COS and verified');expect(state.writes).toHaveLength(1);});
for(const failure of ['badReceipt','badReadback'])test(failure+' freezes the form until verified refresh and never automatically retries',async({page})=>{const {workspace,state}=await mount(page);const form=await add(workspace);state[failure]=true;await confirm(form);await expect(workspace.getByRole('alert')).toContainText('will not be repeated automatically');await expect(form.getByRole('button',{name:'Save pending request'})).toBeDisabled();expect(state.writes).toHaveLength(1);state[failure]=false;await form.getByRole('button',{name:'Refresh pending requests'}).click();await expect(form).toHaveCount(0);expect(state.writes).toHaveLength(1);});

test('definite rejection retains an editable draft and requires fresh source review',async({page})=>{const {workspace,state}=await mount(page);const form=await add(workspace);state.failPost=true;await confirm(form);await expect(workspace.getByRole('alert')).toContainText('Your draft is retained');await expect(form.getByLabel('Unit label',{exact:true})).toHaveValue('004');await expect(form.getByLabel('Unit label',{exact:true})).toBeEditable();await expect(form.getByRole('button',{name:'Save pending request'})).toBeDisabled();state.failPost=false;await form.getByRole('button',{name:'Refresh source and review'}).click();await expect(form.getByLabel('Unit label',{exact:true})).toHaveValue('004');await confirm(form);await expect(workspace).toContainText('Request saved in COS and verified');expect(state.writes).toHaveLength(2);expect(state.writes[1].body.requestId).toBe(state.writes[0].body.requestId);});
for(const mode of ['mismatchReceipt','wrongActor'])test(mode+' cannot become a success through recovery',async({page})=>{const {workspace,state}=await mount(page);const form=await add(workspace);state[mode]=true;await confirm(form);await expect(workspace.getByRole('alert')).toContainText('will not be repeated automatically');await form.getByRole('button',{name:'Refresh pending requests'}).click();await expect(workspace.getByRole('alert')).toContainText('remains blocked');await expect(form).toBeVisible();await expect(form.getByRole('button',{name:'Save pending request'})).toBeDisabled();expect(state.writes).toHaveLength(1);});
test('shared input rules reject invalid unit syntax and private-like values before confirmation',async({page})=>{const {workspace,state}=await mount(page);const form=await add(workspace);await form.getByLabel('Unit label',{exact:true}).fill('001/A');await expect(form.getByRole('checkbox')).toBeDisabled();await form.getByLabel('Unit label',{exact:true}).fill('004');await form.getByLabel('Site label',{exact:true}).fill('Contact Yard');await expect(form.getByRole('checkbox')).toBeDisabled();expect(state.writes).toEqual([]);});
test('pending status and exact request read survive the recent-request list limit',async({page})=>{const {workspace,state}=await mount(page);await workspace.getByRole('button',{name:'Solar Pole 72 003',exact:true}).first().click();await workspace.getByRole('button',{name:'Request tracker change'}).click();const form=workspace.getByRole('region',{name:'Edit tracker request',exact:true});await form.getByLabel('Site label',{exact:true}).fill('Next yard');state.truncated=true;await confirm(form);await expect(workspace).toContainText('Request saved in COS and verified');await expect(workspace.locator('tbody tr').first()).toContainText('1 pending');await expect(workspace.getByRole('button',{name:'Request tracker change'})).toBeDisabled();const pending=workspace.getByRole('region',{name:'Pending requests for selected unit'});await expect(pending).toContainText('Solar Pole 72 003');expect(state.reads).toContain('/api/unit-tracker/'+id);});
test('stale-source recovery preserves newer untouched fields and re-reviews only the intended change',async({page})=>{const {workspace,state}=await mount(page);await workspace.getByRole('button',{name:'Solar Pole 72 003',exact:true}).first().click();await workspace.getByRole('button',{name:'Request tracker change'}).click();const form=workspace.getByRole('region',{name:'Edit tracker request',exact:true});await form.getByLabel('Site label',{exact:true}).fill('My requested yard');state.failPost=true;await confirm(form);await expect(workspace.getByRole('alert')).toContainText('Your draft is retained');state.source.fields.customerLabel='Newer manual customer';state.source.sourceRevision='cccccccc-cccc-4ccc-8ccc-cccccccccccc';state.failPost=false;await form.getByRole('button',{name:'Refresh source and review'}).click();await expect(form.getByLabel('Customer',{exact:true})).toHaveValue('Newer manual customer');await expect(form.getByLabel('Site label',{exact:true})).toHaveValue('My requested yard');await expect(form.getByRole('checkbox')).not.toBeChecked();await confirm(form);await expect(workspace).toContainText('Request saved in COS and verified');expect(state.writes[1].body.changes).toEqual({siteLabel:'My requested yard'});expect(state.writes[1].body.expectedSourceRevision).toBe('cccccccc-cccc-4ccc-8ccc-cccccccccccc');expect(state.source.fields.customerLabel).toBe('Newer manual customer');});

for(const options of [{unavailable:true},{queue:false}])test('unavailable pending store is never described as confirmed empty '+JSON.stringify(options),async({page})=>{const {workspace}=await mount(page,options);const pending=workspace.getByRole('region',{name:'Saved pending tracker requests'});await expect(pending).toContainText('Saved pending requests could not be verified.');await expect(pending).not.toContainText('No saved pending requests.');});
test('pending list loading, confirmed empty and read failure remain distinct',async({page})=>{const {workspace,state}=await mount(page,{holdRead:true});const pending=workspace.getByRole('region',{name:'Saved pending tracker requests'});await expect(pending).toContainText('Checking saved pending requests…');await expect(pending).not.toContainText('No saved pending requests.');state.holdRead=false;state.releaseRead();await expect(pending).toContainText('No saved pending requests.');state.failRead=true;await workspace.getByRole('button',{name:'Refresh tracker',exact:true}).click();await expect(pending).toContainText('Saved pending requests could not be verified.');await expect(pending).not.toContainText('No saved pending requests.');});
test('filtered unit count uses singular only for one result',async({page})=>{const {workspace}=await mount(page);await expect(workspace.getByText('2 units',{exact:true})).toBeVisible();await workspace.getByRole('textbox',{name:'Search Unit Tracker'}).fill('Current Owner yard');await expect(workspace.getByText('1 unit',{exact:true})).toBeVisible();await workspace.getByRole('textbox',{name:'Search Unit Tracker'}).fill('no matching fixture');await expect(workspace.getByText('0 units',{exact:true})).toBeVisible();});
