import test from 'node:test';
import assert from 'node:assert/strict';
import {trackerContract,trackerWorkbookId,trackerAccess,checkedTrackerSnapshot,checkedTrackerRequest,trackerDraft,newTrackerDraft,trackerChanges,trackerDraftProblem,trackerRequestPayload,trackerRequestMatches,trackerInventory} from '../src/unitTracker.ts';
const unitId='11111111-1111-4111-8111-111111111111',sourceRevision='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',requestId='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
const source=()=>({unitId,sourceRevision,pendingRequestId:null,sourceIdentity:{sourceSystem:'google_sheet_tracker',sourceRecordId:'google_sheet:'+trackerWorkbookId+':10:Solar Pole 72|003'},family:'SOLAR POLES & SKIDS',fullVariant:'Solar Pole 72',unitLabel:'003',fields:{placement:'FIELD',street:'100 Example Road',city:'Houston',state:'TX',zip:null,siteLabel:'Yard',customerLabel:'Example Customer'}});
const snapshot=()=>({contract:trackerContract,workbookId:trackerWorkbookId,connector:{enabled:false,state:'awaiting_sheets_connection'},queueEnabled:true,sources:[source()],requests:[],sourcesTruncated:false,requestsTruncated:false,sourcesHeld:0});
test('Unit Tracker requires explicit backend support and Owner or verified IT session',()=>{for(const role of ['Owner','IT'])assert.equal(trackerAccess({authorized:true,role,features:{unitTracker:true}}),true);for(const session of [{authorized:true,role:'Service',features:{unitTracker:true}},{authorized:true,role:'IT',features:{}},{authorized:false,role:'Owner',features:{unitTracker:true}},null])assert.equal(trackerAccess(session),false);});
test('source parsing rejects other workbook and malformed connector states',()=>{assert.equal(checkedTrackerSnapshot(snapshot()).sources[0].unitLabel,'003');for(const change of [s=>s.workbookId='legacy_2026',s=>s.connector.enabled=true,s=>s.connector.state='synced',s=>s.sources[0].sourceIdentity.sourceRecordId='google_sheet:legacy_2026:10:Solar Pole 72|003',s=>s.sources.push(source()),s=>s.sourcesHeld=-1]){const s=snapshot();change(s);assert.throws(()=>checkedTrackerSnapshot(s));}});
test('changes preserve every untouched field, while a deliberate blank requests only that clear',()=>{const s=source(),draft=trackerDraft(s);assert.deepEqual(trackerChanges(draft,s),{});draft.siteLabel='';assert.deepEqual(trackerChanges(draft,s),{siteLabel:null});draft.customerLabel='Next customer';assert.deepEqual(trackerChanges(draft,s),{siteLabel:null,customerLabel:'Next customer'});const payload=trackerRequestPayload(draft,s,requestId,true);assert.equal(payload.unitId,unitId);assert.equal(payload.expectedSourceRevision,sourceRevision);assert.equal(payload.identity,undefined);assert.equal(payload.changes.street,undefined);assert.throws(()=>trackerRequestPayload(draft,s,requestId,false));});
test('add requests include full identity and remain proposals with no invented native ID',()=>{const d={...newTrackerDraft(),family:'SOLAR POLES & SKIDS',fullVariant:'Solar Pole 72',unitLabel:'004'};assert.equal(trackerDraftProblem(d,null),'');const p=trackerRequestPayload(d,null,requestId,true);assert.deepEqual(p,{requestId,kind:'add',identity:{family:d.family,fullVariant:d.fullVariant,unitLabel:d.unitLabel},changes:{placement:'SHOP'}});d.placement='FIELD';assert.match(trackerDraftProblem(d,null),/street address/);d.street='100 Example Road';d.state='TX';d.zip='77001';assert.equal(trackerDraftProblem(d,null),'');});
test('secret-like fields and formulas cannot be staged by the form',()=>{for(const value of ['=IMPORTXML(A1)','gate code 1234','password qwerty','https://example.test','a@b.com']){const d={...newTrackerDraft(),family:'Stands',fullVariant:'Solar Stand',unitLabel:'001',siteLabel:value};assert.match(trackerDraftProblem(d,null),/passwords/);}});
test('inventory association uses UUID only and never collapses related models or matching labels',()=>{const s=source(),other='22222222-2222-4222-8222-222222222222';const rows=trackerInventory({inventoryItems:[{id:unitId,unitNumber:'Solar Pole 72 003',status:'field'},{id:other,unitNumber:'Solar Pole 72 003',status:'shop'}]},[s],[]);assert.equal(rows.length,2);assert.equal(rows[0].source,s);assert.equal(rows[1].source,null);assert.throws(()=>trackerInventory({inventoryItems:[{id:unitId,unitNumber:'003'},{id:unitId,unitNumber:'003'}]},[s],[]));});
test('receipt must match immutable request identity and changed fields; partial or published receipt fails',()=>{const s=source(),d=trackerDraft(s);d.siteLabel='Next yard';const p=trackerRequestPayload(d,s,requestId,true);const r={requestId,kind:'update',status:'awaiting_sheets_connection',createdAt:'2026-10-09T04:00:00Z',identity:{unitId,family:s.family,fullVariant:s.fullVariant,unitLabel:s.unitLabel,sourceRecordId:s.sourceIdentity.sourceRecordId},expectedSourceRevision:sourceRevision,changes:p.changes,before:s.fields,proposed:{...s.fields,...p.changes}};assert.equal(trackerRequestMatches(checkedTrackerRequest(r),p),true);assert.equal(trackerRequestMatches({...r,expectedSourceRevision:requestId},p),false);assert.equal(trackerRequestMatches({...r,changes:{siteLabel:'Wrong yard'}},p),false);assert.throws(()=>checkedTrackerRequest({...r,status:'synced'}));assert.throws(()=>checkedTrackerRequest({...r,before:{}}));});
test('client shares strict backend bounds, syntax, formula and privacy validation before confirmation',()=>{
 for(const change of [{unitLabel:'001/A'},{unitLabel:'a'.repeat(41)},{siteLabel:'Contact Yard'},{siteLabel:'+1+1'},{siteLabel:'10.2.3.4'},{city:'A'.repeat(121)}]){const draft={...newTrackerDraft(),family:'Stands',fullVariant:'Solar Stand',unitLabel:'001',...change};assert.notEqual(trackerDraftProblem(draft,null),'');}
});
test('decimal labels retain their exact identity in source parsing and pending additions',()=>{for(const label of ['029.2','023.1']){const snap=snapshot();snap.sources[0].unitLabel=label;snap.sources[0].sourceIdentity.sourceRecordId='google_sheet:'+trackerWorkbookId+':10:Solar Pole 72|'+label;assert.equal(checkedTrackerSnapshot(snap).sources[0].unitLabel,label);const draft={...newTrackerDraft(),family:'SOLAR POLES & SKIDS',fullVariant:'Solar Pole 72',unitLabel:label};assert.equal(trackerDraftProblem(draft,null),'');assert.equal(trackerRequestPayload(draft,null,requestId,true).identity.unitLabel,label);}});
