function renderOwner(){if(state.profile?.role!=='owner')return;$('ownerPrepStatus').innerHTML=state.preps.length?state.preps.map(p=>'<div class="item"><div class="row"><b>MHelpDesk Ticket #'+esc(p.ticket_no)+'</b> '+(p.status==='draft'?'<span class="pill amber">IT EQUIPMENT PREP</span>':p.status==='released'?'<span class="pill green">READY FOR SERVICE CHECKOUT</span>':'<span class="pill">EQUIPMENT VERIFIED</span>')+'</div><div class="small">'+esc(p.site||'No site')+' · '+(p.prep_items||[]).map(i=>i.purpose+' '+i.equipment_type+(i.unit_tag?' '+i.unit_tag:'')).join(' · ')+'</div></div>').join(''):'<div class="warn">No prepared equipment records yet.</div>';$('reports').innerHTML=state.reports.length?state.reports.map(r=>'<div class="item"><b>'+esc(r.kind)+'</b><div>'+esc(r.actor_name||'Technician')+'</div><div class="small">'+new Date(r.created_at).toLocaleString()+'</div><div>'+esc(r.text)+'</div></div>').join(''):'<div class="warn">No reports yet.</div>';ensureStartFreshCard()}
async function createTech(){msg('userMessage','');const username=normalizeUsername($('newTechUsername').value);const body={action:'create',full_name:$('newTechName').value.trim(),email:authId(username),role:$('newTechRole').value,password:$('newTechPassword').value};if(!body.full_name||!validUsername(username)||body.password.length<8)return msg('userMessage','Enter a name, a username of 3–32 letters/numbers/dots/dashes/underscores, a role, and a temporary password of at least 8 characters.','bad');setBusy(true);const {data,error}=await db.functions.invoke('admin-user-management',{body});setBusy(false);if(error)return msg('userMessage',error.message,'bad');if(data?.error)return msg('userMessage',data.error,'bad');$('newTechName').value='';$('newTechUsername').value='';$('newTechPassword').value='';msg('userMessage','Technician login created for username '+username+'.','ok');await refreshData()}
function renderUsers(){if(state.profile?.role!=='owner')return;$('userList').innerHTML=state.profiles.length?state.profiles.map(p=>'<div class="usercard"><div><b>'+esc(p.full_name||p.username||'User')+'</b><div class="small">Username: '+esc(p.username||'Not set')+'</div></div><div class="usergrid" style="margin-top:8px"><div><label>Role</label><select id="role_'+p.user_id+'"><option value="service" '+(p.role==='service'?'selected':'')+'>Service Tech</option><option value="it" '+(p.role==='it'?'selected':'')+'>IT Tech</option><option value="owner" '+(p.role==='owner'?'selected':'')+'>Owner/Admin</option><option value="pending" '+(p.role==='pending'?'selected':'')+'>Pending</option></select></div><div><label>Active</label><select id="active_'+p.user_id+'"><option value="true" '+(p.active?'selected':'')+'>Active</option><option value="false" '+(!p.active?'selected':'')+'>Disabled</option></select></div><div><label>&nbsp;</label><button class="mini" style="width:100%" onclick="saveUserAccess(\''+p.user_id+'\')">Save Access</button></div></div><div class="grid" style="margin-top:8px"><div><label>Set New Password</label><input id="reset_'+p.user_id+'" type="password" placeholder="8+ characters"></div><div><label>&nbsp;</label><button class="mini" style="width:100%" onclick="resetUserPassword(\''+p.user_id+'\')">Reset Password</button></div></div></div>').join(''):'<div class="warn">No users yet.</div>'}
async function saveUserAccess(id){const role=$('role_'+id).value,active=$('active_'+id).value==='true';const {data,error}=await db.functions.invoke('admin-user-management',{body:{action:'set_access',user_id:id,role,active}});if(error||data?.error)return alert(error?.message||data.error);await refreshData();alert('Access updated.')}
async function resetUserPassword(id){const password=$('reset_'+id).value;if(password.length<8)return alert('Password must be at least 8 characters.');const {data,error}=await db.functions.invoke('admin-user-management',{body:{action:'reset_password',user_id:id,password}});if(error||data?.error)return alert(error?.message||data.error);$('reset_'+id).value='';alert('Password reset.')}
function ensureStartFreshCard(){if($('ownerResetCard'))return;const card=document.createElement('div');card.id='ownerResetCard';card.className='card';card.innerHTML='<h2 style="margin-top:0">Start Fresh / Clear Test Data</h2><div class="warn"><b>Owner only.</b><div class="small">Clears all equipment prep records, equipment checkout verifications, Owner reports, and morning checks. Technician accounts, usernames, roles, and passwords are kept.</div></div><button class="btn danger" onclick="startFresh()">Start Fresh — Clear Operational Data</button>';const reportCard=$('reports')?.closest('.card');if(reportCard)reportCard.after(card);else $('view-owner')?.appendChild(card)}
async function startFresh(){if(state.profile?.role!=='owner')return;const answer=prompt('This clears ALL equipment prep, equipment verification history, Owner reports, and morning checks. Technician accounts and passwords will be kept. Type RESET to continue.');if(answer!=='RESET')return;setBusy(true);const {error}=await db.rpc('owner_start_fresh');setBusy(false);if(error)return alert(error.message);state.matched=[];state.sessionClosed=[];await refreshData();alert('Started fresh. Operational/test data was cleared. Technician accounts were kept.')}

$('truckChecks').innerHTML=TRUCK.map((x,i)=>'<div class="check"><input class="truckBox" type="checkbox" onchange="updateMorningStatus()"><div><b>'+esc(x)+'</b></div></div>').join('');
$('trailerChecks').innerHTML=TRAILER.map((x,i)=>'<div class="check"><input class="trailerBox" type="checkbox" onchange="updateMorningStatus()"><div><b>'+esc(x)+'</b></div></div>').join('');
renderDraftNeeds();init();
