const historyEvidenceDb = window.__techCheckDb;
const HISTORY_EVIDENCE_BUCKET='handoff-evidence';
let historyEvidenceTimer=null;

function heEsc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'})[c]);}
function heNorm(v){return String(v||'').trim().toLowerCase().replace(/[^a-z0-9]/g,'');}

function heStyles(){if(document.getElementById('historyEvidenceStyles'))return;const s=document.createElement('style');s.id='historyEvidenceStyles';s.textContent=`.history-proof-btn{margin-top:8px}.history-proof{margin-top:8px;border:1px solid #cfdbe5;border-radius:10px;background:#f8fbfd;padding:9px}.history-proof-section{margin-top:9px}.history-proof-section:first-child{margin-top:0}.history-proof-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:6px;margin-top:6px}.history-proof-img{background:#fff;border:1px solid #dce4ea;border-radius:8px;overflow:hidden}.history-proof-img img{display:block;width:100%;height:85px;object-fit:cover}.history-proof-img div{padding:4px;font-size:9px}.history-proof-sig{background:#fff;border:1px solid #b9d9c6;border-radius:8px;padding:7px;margin-top:6px}.history-proof-sig img{display:block;width:100%;max-height:90px;object-fit:contain;margin-top:5px}@media(max-width:520px){.history-proof-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}`;document.head.appendChild(s);}

function heTicketFromCard(card){const txt=card.querySelector('b')?.textContent||'';const m=txt.match(/Ticket\s*#\s*([^\s]+)/i);return m?m[1]:'';}
function heScan(){document.querySelectorAll('.mgmt-ticket').forEach(card=>{if(card.querySelector('.history-proof-btn'))return;const ticket=heTicketFromCard(card);if(!ticket)return;const btn=document.createElement('button');btn.type='button';btn.className='mini full history-proof-btn';btn.textContent='View Photo & Signature Proof';btn.dataset.ticket=ticket;card.appendChild(btn);});}
function heSchedule(){clearTimeout(historyEvidenceTimer);historyEvidenceTimer=setTimeout(heScan,80);}
function heObserve(id){const n=document.getElementById(id);if(!n||n.dataset.historyEvidenceObserved==='true')return;n.dataset.historyEvidenceObserved='true';new MutationObserver(heSchedule).observe(n,{childList:true,subtree:true});}

async function heRows(ticket){const{data:preps,error}=await historyEvidenceDb.from('prep_tickets').select('id,ticket_no').order('created_at',{ascending:false});if(error)return[];const prep=(preps||[]).find(p=>heNorm(p.ticket_no)===heNorm(ticket));if(!prep)return[];const{data:rows}=await historyEvidenceDb.from('handoff_evidence').select('*').eq('prep_ticket_id',prep.id).order('created_at',{ascending:true});const out=rows||[];for(const r of out){const{data:signed}=await historyEvidenceDb.storage.from(HISTORY_EVIDENCE_BUCKET).createSignedUrl(r.storage_path,3600);r.url=signed?.signedUrl||'';}return out;}
function heStage(title,rows,stage){const set=rows.filter(r=>r.stage===stage),photos=set.filter(r=>r.kind==='photo'),sig=[...set].reverse().find(r=>r.kind==='signature');return `<div class="history-proof-section"><b>${heEsc(title)}</b>${photos.length?`<div class="history-proof-grid">${photos.map(r=>`<div class="history-proof-img">${r.url?`<img src="${heEsc(r.url)}" alt="Handoff proof">`:''}<div>${heEsc(r.created_by_name)}<br>${new Date(r.created_at).toLocaleString()}</div></div>`).join('')}</div>`:'<div class="small">No photos recorded.</div>'}${sig?`<div class="history-proof-sig"><b>Signed by ${heEsc(sig.created_by_name)}</b><div class="small">${new Date(sig.created_at).toLocaleString()}</div>${sig.url?`<img src="${heEsc(sig.url)}" alt="Signature">`:''}</div>`:'<div class="small">No signature recorded.</div>'}</div>`;}

document.addEventListener('click',async ev=>{const btn=ev.target.closest('.history-proof-btn');if(!btn)return;const card=btn.closest('.mgmt-ticket');let proof=card.querySelector('.history-proof');if(proof){proof.remove();btn.textContent='View Photo & Signature Proof';return;}btn.disabled=true;btn.textContent='Loading proof…';const rows=await heRows(btn.dataset.ticket);proof=document.createElement('div');proof.className='history-proof';proof.innerHTML=rows.length?heStage('IT — Prepared & Sent',rows,'it')+heStage('Service — Received & Verified',rows,'service'):'<div class="small">No photo/signature proof was recorded for this ticket.</div>';card.appendChild(proof);btn.disabled=false;btn.textContent='Hide Photo & Signature Proof';});

function heInstall(){heStyles();heObserve('itWorkQueueCard');heObserve('serviceHistoryCard');heScan();setTimeout(()=>{heObserve('itWorkQueueCard');heObserve('serviceHistoryCard');heScan();},500);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',heInstall);else heInstall();
