alter table public.camera_devices
  add column if not exists external_device_id text,
  add column if not exists source_status text,
  add column if not exists source_last_seen_at timestamptz,
  add column if not exists source_metadata jsonb not null default '{}'::jsonb;

create unique index if not exists camera_devices_source_external_device_uidx
  on public.camera_devices(source, external_device_id)
  where external_device_id is not null;

create table if not exists public.camera_integrations (
  id bigint generated by default as identity primary key,
  provider text not null unique,
  server_host text not null,
  server_port integer,
  enabled boolean not null default false,
  username_secret_id uuid,
  password_secret_id uuid,
  webhook_secret_id uuid,
  last_sync_at timestamptz,
  last_sync_status text,
  last_error text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.camera_integrations enable row level security;

drop policy if exists camera_integrations_owner_it_read on public.camera_integrations;
create policy camera_integrations_owner_it_read
on public.camera_integrations
for select
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.user_id = (select auth.uid())
      and p.active = true
      and p.role::text = any(array['owner'::text,'it'::text])
  )
);

create table if not exists public.camera_integration_events (
  id bigint generated by default as identity primary key,
  provider text not null,
  external_device_id text,
  camera_device_id bigint references public.camera_devices(id) on delete set null,
  event_type text,
  event_code text,
  observed_at timestamptz,
  received_at timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb,
  processed boolean not null default false,
  processing_note text
);

create index if not exists camera_integration_events_provider_received_idx
  on public.camera_integration_events(provider, received_at desc);
create index if not exists camera_integration_events_device_idx
  on public.camera_integration_events(camera_device_id, received_at desc);

alter table public.camera_integration_events enable row level security;

drop policy if exists camera_integration_events_owner_it_read on public.camera_integration_events;
create policy camera_integration_events_owner_it_read
on public.camera_integration_events
for select
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.user_id = (select auth.uid())
      and p.active = true
      and p.role::text = any(array['owner'::text,'it'::text])
  )
);

create or replace function public.save_reconeyez_credentials(
  p_username text,
  p_password text
)
returns void
language plpgsql
security definer
set search_path = public, vault, extensions
as $$
declare
  u_id uuid;
  p_id uuid;
  w_id uuid;
  w_secret text;
begin
  if nullif(trim(p_username),'') is null or nullif(p_password,'') is null then
    raise exception 'Reconeyez username and password are required';
  end if;

  select id into u_id from vault.secrets where name='reconeyez_username' limit 1;
  if u_id is null then
    u_id := vault.create_secret(trim(p_username), 'reconeyez_username', 'Reconeyez NA integration username');
  else
    perform vault.update_secret(u_id, trim(p_username));
  end if;

  select id into p_id from vault.secrets where name='reconeyez_password' limit 1;
  if p_id is null then
    p_id := vault.create_secret(p_password, 'reconeyez_password', 'Reconeyez NA integration password');
  else
    perform vault.update_secret(p_id, p_password);
  end if;

  select id into w_id from vault.secrets where name='reconeyez_webhook_token' limit 1;
  if w_id is null then
    w_secret := encode(extensions.gen_random_bytes(32),'hex');
    w_id := vault.create_secret(w_secret, 'reconeyez_webhook_token', 'Reconeyez inbound webhook token');
  end if;

  insert into public.camera_integrations(
    provider,server_host,server_port,enabled,
    username_secret_id,password_secret_id,webhook_secret_id,
    updated_at
  )
  values(
    'reconeyez','na.reconeyez.com',9028,true,
    u_id,p_id,w_id,now()
  )
  on conflict(provider) do update set
    server_host=excluded.server_host,
    server_port=excluded.server_port,
    enabled=true,
    username_secret_id=excluded.username_secret_id,
    password_secret_id=excluded.password_secret_id,
    webhook_secret_id=coalesce(public.camera_integrations.webhook_secret_id,excluded.webhook_secret_id),
    updated_at=now();
end;
$$;

revoke all on function public.save_reconeyez_credentials(text,text) from public, anon, authenticated;
grant execute on function public.save_reconeyez_credentials(text,text) to service_role;

create or replace function public.get_reconeyez_integration_secrets()
returns table(
  server_host text,
  server_port integer,
  username text,
  password text,
  webhook_secret text
)
language sql
security definer
set search_path = public, vault
as $$
  select
    ci.server_host,
    ci.server_port,
    u.decrypted_secret,
    p.decrypted_secret,
    w.decrypted_secret
  from public.camera_integrations ci
  left join vault.decrypted_secrets u on u.id=ci.username_secret_id
  left join vault.decrypted_secrets p on p.id=ci.password_secret_id
  left join vault.decrypted_secrets w on w.id=ci.webhook_secret_id
  where ci.provider='reconeyez'
  limit 1;
$$;

revoke all on function public.get_reconeyez_integration_secrets() from public, anon, authenticated;
grant execute on function public.get_reconeyez_integration_secrets() to service_role;

do $$
declare
  w_id uuid;
  w_secret text;
begin
  select id into w_id from vault.secrets where name='reconeyez_webhook_token' limit 1;
  if w_id is null then
    w_secret := encode(extensions.gen_random_bytes(32),'hex');
    w_id := vault.create_secret(w_secret, 'reconeyez_webhook_token', 'Reconeyez inbound webhook token');
  end if;

  insert into public.camera_integrations(provider,server_host,server_port,enabled,webhook_secret_id)
  values('reconeyez','na.reconeyez.com',9028,false,w_id)
  on conflict(provider) do update set
    server_host='na.reconeyez.com',
    server_port=9028,
    webhook_secret_id=coalesce(public.camera_integrations.webhook_secret_id,excluded.webhook_secret_id),
    updated_at=now();
end $$;
