import {useEffect,useMemo,useRef,useState} from 'react';
import {cameraOverview,resourceBreakdown,type CameraUnitGroup} from './cameraHealthCounts';
import {cameraColors,cameraTime,fieldCameraHealth,type Health,type FieldHealthUnit} from './fieldCameraHealth';
import {providerRecord,providerState,unclassifiedProviderReport,serviceState,resourceKind,unitEvidenceLabel,cameraEvidenceLabel,serviceEvidenceLabel,observationAge,type CameraRow,type UnitEvidence} from './cameraEvidence';
type Props={health:Health;now:number;units:FieldHealthUnit[]|null;createTicket?:(type:'SERVICE'|'PICKUP'|'DELIVERY'|'SWAP',id:string)=>void};
const statusColor=(state:string)=>state==='online'?cameraColors.online:state==='offline'?cameraColors.offline:state==='degraded'||state==='service'?'#f1c36d':cameraColors.unknown;
export function UnitEvidenceDetails({classification}:{classification:UnitEvidence|null}){
  if(!classification)return null;
  return <div className='camera-unit-evidence'><p className={'camera-status-pill camera-status-'+classification.state} style={{color:statusColor(classification.state)}}>{unitEvidenceLabel(classification)}</p>{classification.scope==='unknown'&&<p className='placement-warning'>LOCATION REVIEW · Field or shop placement is not verified.</p>}<p>{cameraEvidenceLabel(classification.cameraState)}. Expected channel coverage is not established.</p><p>{serviceEvidenceLabel(classification.serviceState)}. Service ports do not verify camera video.</p>{classification.recorderOffline&&<p role='note'>Recorder OFFLINE observation. Review the recorder separately from camera channel evidence.</p>}</div>;
}
export function CameraResourceObservations({rows,now,trusted=true}:{rows:CameraRow[];now:number;trusted?:boolean}){
  return <div className='camera-device-cards'>{rows.map(row=>{
    const evidence=row.evidence,service=row.serviceEvidence||(evidence?.kind==='service_port'?evidence:undefined),provider=trusted?providerState(row,now):'verifying',port=trusted?serviceState(row,now):'verifying';
    const unclassified=trusted?unclassifiedProviderReport(row):undefined;
    const kind=resourceKind(row),resource=kind==='recorders'?'RECORDER':kind==='detectors'?'DETECTOR':kind==='cameras'?'CAMERA':'PROVIDER';
    return <article key={row.id}><div><strong>{row.name}</strong><b style={{color:statusColor(provider)}}>{resource} {provider==='verifying'?'NOT VERIFIED':provider.toUpperCase()}</b></div><p>{[row.type,row.organization].filter(Boolean).join(' · ')||'Resource type not verified'}</p>
      {trusted&&providerRecord(row)&&evidence?<><p>{evidence.source} · Last reported {resource.toLowerCase()} state: <b>{String(evidence.status||'unknown').toUpperCase()}</b></p><p>{cameraTime(evidence.observedAt,now)} · {observationAge(evidence.observedAt,now)}</p><small>Last recorded successful provider connection: {cameraTime(evidence.lastOnlineAt,now)}</small></>:unclassified?<><p>{unclassified.source} resource last reported <b>{unclassified.status.toUpperCase()}</b> at {cameraTime(unclassified.observedAt,now)}.</p><p>{observationAge(unclassified.observedAt,now)}</p><p>Hardware type and camera/channel status remain unverified. This saved report does not verify live video.</p><small>Last recorded successful provider connection: {cameraTime(unclassified.lastOnlineAt,now)}</small></>:<p>No verified provider camera/recorder observation.</p>}
      {kind==='recorders'&&<p>Camera channel status unavailable from this recorder observation.</p>}
      <p>{serviceEvidenceLabel(port)}{service?' · '+service.source:''}</p>{service&&<><p>Last reported service result: {service.status.toUpperCase()} · {cameraTime(service.observedAt,now)} · {observationAge(service.observedAt,now)}</p><small>Last recorded service-port success: {cameraTime(service.lastOnlineAt,now)}. Service reachability is not camera-status proof.</small></>}
    </article>;
  })}</div>;
}
export default function CameraHealthOverview({health,now,units,createTicket}:Props){
  const overview=useMemo(()=>cameraOverview(health,now),[health,now]);
  const [filter,setFilter]=useState('all'),[search,setSearch]=useState(''),[selectedKey,setSelectedKey]=useState(''),[ticketType,setTicketType]=useState<'SERVICE'|'PICKUP'|'DELIVERY'|'SWAP'>('SERVICE');
  const dialog=useRef<HTMLDialogElement|null>(null),opener=useRef<HTMLElement|null>(null);
  const selected=overview.groups.find(group=>group.key===selectedKey);
  const matches=selected&&units?units.filter(unit=>{const info=fieldCameraHealth(unit,units,health,now);return info.identity==='matched'&&info.rows.length===selected.rows.length&&info.rows.every(row=>selected.rows.some(other=>String(row.id)===String(other.id)));}):[];
  const fieldUnit=matches.length===1?matches[0]:null;
  const groups=overview.groups.filter(group=>{
    const active=['field','unknown'].includes(group.scope);
    const inFilter=filter==='unlinked'?!group.linkedIdentity:!group.linkedIdentity?false:
      filter==='shop'||filter==='inactive'?group.scope===filter:
      filter==='placement'?group.scope==='unknown':!active?false:
      filter==='all'?true:filter==='unknown'?!['online','offline'].includes(group.providerState):
      filter==='service'?group.providerState==='verifying'&&group.serviceState==='online':
      filter==='mixed'?group.providerState==='degraded':group.providerState===filter;
    return inFilter&&[group.name,group.site,...group.rows.map(row=>row.name)].join(' ').toLowerCase().includes(search.trim().toLowerCase());
  });
  const close=()=>{setSelectedKey('');dialog.current?.close();opener.current?.focus({preventScroll:true});};
  useEffect(()=>{if(selectedKey&&selected){if(!dialog.current?.open)dialog.current?.showModal();}else if(selectedKey){setSelectedKey('');dialog.current?.close();}},[selectedKey,Boolean(selected)]);
  const open=(group:CameraUnitGroup)=>{opener.current=document.activeElement as HTMLElement;setTicketType('SERVICE');setSelectedKey(group.key);};
  const total=(key:'monitored'|'online'|'offline'|'unknown')=>overview.scopeVerified?overview.summary[key]:'—';
  return <div className='camera-overview'>
    <div className='camera-overview-intro'><div><h3>How is the fleet doing?</h3><p>One card per saved unit. Provider system status, camera/detector observations, and service reachability are separate.</p></div><small>Last refresh<br/><b>{cameraTime(health.refreshedAt,now)}</b></small></div>
    {!overview.scopeVerified&&<p className='operations-error' role='alert'>Source-separated inventory scope is not verified by this response. Totals stay unavailable until confirmed-field, unresolved, shop and inactive records reconcile.</p>}
    <div className='camera-unit-kpis' aria-label='Provider system unit totals'>
      {[['monitored','Active / unresolved units','all'],['online','Provider systems online','online'],['offline','Provider systems offline','offline'],['unknown','Provider review','unknown']].map(([key,label,state])=><button key={key} className={'camera-unit-kpi '+(filter===state?'selected':'')} aria-pressed={filter===state} onClick={()=>setFilter(state)}><span>{label}</span><b className={'camera-status-'+state} style={state==='all'?{}:{color:cameraColors[state as keyof typeof cameraColors]}}>{total(key as 'monitored'|'online'|'offline'|'unknown')}</b><small>{state==='online'?'Reported provider resources online':state==='offline'?'Reported provider resources offline':state==='unknown'?'Mixed, service-only or unverified':'Confirmed field + location review'}</small></button>)}
    </div>
    <section className='camera-record-breakdown' aria-label='Individual camera coverage'>
      <div className='camera-actual-count'><b>{overview.scopeVerified?overview.cameras.total:'—'}</b><div><strong>Reported camera records</strong><small>{overview.cameras.online} online · {overview.cameras.offline} offline · {overview.cameras.unknown} unverified</small></div></div>
      <p>{overview.kinds.detectors} detectors · {overview.kinds.recorders} recorders · {overview.kinds.unitInventory} unit inventory records{overview.kinds.other?' · '+overview.kinds.other+' other resources':''}</p>
      <p className='camera-unit-coverage'>Camera/detector evidence by active or unresolved unit: {overview.coverage.cameraOnline} online · {overview.coverage.cameraOffline} offline · {overview.coverage.cameraMixed} mixed/unverified · {overview.coverage.cameraUnavailable} with channel status unavailable.</p>
      <p className='camera-service-coverage'>{overview.coverage.serviceReachable} of {overview.coverage.review} systems needing provider review have reachable service ports. {overview.coverage.degraded} systems have mixed provider status.</p>
      <small>NVR status describes the recorder. Service-port status describes reachability. Neither establishes camera channel coverage. Counts describe reported records and never prove all cameras are healthy.</small>
      {overview.scopeVerified&&<details><summary>How these totals add up</summary><p>{health.inventory!.allRecords} inventory records = {health.inventory!.activeFieldRecords} confirmed-field records + {health.inventory!.activeShopRecords} shop/root records + {health.inventory!.inactiveRecords} inactive records + {health.inventory!.unknownScopeRecords||0} location-review records.</p><p>{overview.scopes.field} confirmed-field units + {overview.scopes.unknown} location-review units = {overview.summary.monitored} active / unresolved unit groups. {overview.scopes.shop} shop/root and {overview.scopes.inactive} inactive unit groups are excluded from operational totals.</p><p>{overview.summary.online} provider online + {overview.summary.offline} provider offline + {overview.summary.unknown} provider review = {overview.summary.monitored} groups. Mixed provider observations remain in review, even when individual camera outages are present. {overview.records} resource records are grouped by exact saved unit key.</p>{overview.unlinked>0&&<p>{overview.unlinked} resources have no unambiguous saved unit key and are excluded from unit totals.</p>}{health.coverageNote&&<p>{health.coverageNote}</p>}</details>}
    </section>
    <div className='camera-overview-toolbar'><input aria-label='Search Camera Health units' placeholder='Search unit, site or device…' value={search} onChange={event=>setSearch(event.target.value)}/><select aria-label='Camera Health unit filter' value={filter} onChange={event=>setFilter(event.target.value)}><option value='all'>Active / unresolved units</option><option value='offline'>Provider systems offline</option><option value='unknown'>Provider review</option><option value='online'>Provider systems online</option><option value='mixed'>Mixed provider status</option><option value='service'>Service reachable only</option><option value='placement'>Location review ({overview.scopes.unknown})</option><option value='shop'>Shop / ROOT ({overview.scopes.shop})</option><option value='inactive'>Inactive ({overview.scopes.inactive})</option>{overview.unlinked>0&&<option value='unlinked'>Unlinked resources ({overview.unlinked})</option>}</select><span>{groups.length} shown</span></div>
    <p className='camera-overview-freshness'>The 15-minute window is a presentation threshold for recent observations, not an expected heartbeat. Older Reconeyez and other provider states retain their last reported status and age. Silence does not establish an outage. Refresh reads saved observations; it does not run a test.</p>
    <div className='camera-overview-grid' aria-label='Camera Health unit cards'>{groups.map(group=><button key={group.key} className='camera-overview-card' onClick={()=>open(group)}><div><strong>{group.name}</strong><span className={'camera-status-pill camera-status-'+group.state} style={{color:statusColor(group.state)}}>{unitEvidenceLabel(group)}</span></div>{group.scope==='unknown'&&<p className='placement-warning'>LOCATION REVIEW · Field or shop not verified</p>}<p>{group.scope==='unknown'?'Saved site: ':''}{group.site||'Site not linked'}</p><small>{resourceBreakdown(group.rows)}</small>{!group.linkedIdentity&&<small>Unit identity missing or conflicting; excluded from unit totals.</small>}<small>{cameraEvidenceLabel(group.cameraState)}</small>{group.online+group.offline+group.unknown>0&&<small>{group.online} camera/detector records online · {group.offline} offline · {group.unknown} unverified</small>}<small>{serviceEvidenceLabel(group.serviceState)}</small><small>Latest observation: {cameraTime(group.lastObservedAt,now)} · {observationAge(group.lastObservedAt,now)}</small><b className='camera-card-link'>View unit details →</b></button>)}</div>
    {!groups.length&&<p className='field-map-empty'>No unit groups match this view.</p>}
    {selected&&<dialog ref={dialog} className='camera-overview-detail' aria-label='Camera Health unit details' onCancel={event=>{event.preventDefault();close();}}><div className='camera-detail-top'><div><small>UNIT DETAILS</small><h3>{selected.name}</h3><p>{selected.site||'Site not linked'}</p></div><button className='secondary' onClick={close}>Back to units</button></div><UnitEvidenceDetails classification={selected}/><p>{resourceBreakdown(selected.rows)}</p><CameraResourceObservations rows={selected.rows} now={now} trusted={health.evidenceVersion===2}/>
      {createTicket&&<section className='camera-detail-ticket'><h4>Create a ticket for this unit</h4>{fieldUnit?<><p>Field record: {fieldUnit.unitNumber}. Customer and site are verified again in the ticket draft.</p><select aria-label='Unit detail ticket type' value={ticketType} onChange={event=>setTicketType(event.target.value as typeof ticketType)}><option value='SERVICE'>Service / repair</option><option value='PICKUP'>Pick up</option><option value='DELIVERY'>Install / Delivery</option><option value='SWAP'>Swap out</option></select><button onClick={()=>{const id=fieldUnit.id;close();createTicket(ticketType,id);}}>Create ticket</button></>:<p>No unique current field record is linked to this Camera Health unit. Select the correct unit in Field View before creating its ticket; customer and site will not be guessed.</p>}</section>}
    </dialog>}
  </div>;
}
