import {useCallback,useEffect,useRef,useState} from 'react';
import {api,OperationsApiError} from './api';
import {addressUuid,checkedTrackerRequest,checkedTrackerSnapshot,checkedTrackerDetail,checkedTrackerLookup,newTrackerDraft,trackerAccess,trackerChanges,trackerDraft,trackerDraftProblem,trackerFieldLabels,trackerInventory,trackerRequestMatches,trackerRequestPayload,trackerWorkbookId,type TrackerDraft,type TrackerFields,type TrackerInventory,type TrackerRequest,type TrackerSnapshot,type TrackerSource} from './unitTracker';
import './unitTracker.css';

type Props={session:unknown;show:(message:string)=>void;initialUnitId?:string;onSelectUnit?:(id:string)=>void;openMap:(id:string)=>void;openHealth:(id:string)=>void};
const message=(cause:unknown)=>cause instanceof Error?cause.message:'Unit Tracker could not verify the current records.';
const display=(value:unknown)=>value===null||value===''?'Not recorded':String(value);
const unitName=(identity:{fullVariant:string;unitLabel:string})=>identity.fullVariant+' '+identity.unitLabel;
function RequestDetails({request}:{request:TrackerRequest}){
 return <details className='unit-tracker-request'><summary><strong>{unitName(request.identity)}</strong><span>{request.kind==='add'?'Pending addition':'Pending change'}</span><span className='unit-tracker-status'>Sheets connection required</span></summary><p>Saved in COS {new Date(request.createdAt).toLocaleString()}. This request has not been sent to Google Sheets or applied to fleet records.</p><dl className='unit-tracker-values'>{Object.entries(request.changes).map(([key,value])=><div key={key}><dt>{trackerFieldLabels[key as keyof TrackerFields]}</dt><dd>{request.kind==='update'&&<><span className='unit-tracker-before'>{display(request.before?.[key as keyof TrackerFields])}</span><span aria-label='changes to'> → </span></>}{value===null?'Clear this field':String(value)}</dd></div>)}</dl><small>Request ID: {request.requestId}</small></details>;
}
export default function UnitTrackerWorkspace({session,show,initialUnitId,onSelectUnit,openMap,openHealth}:Props){
 const allowed=trackerAccess(session);
 const [snapshot,setSnapshot]=useState<TrackerSnapshot|null>(null),[inventory,setInventory]=useState<TrackerInventory[]>([]);
 const [query,setQuery]=useState(''),[placement,setPlacement]=useState('ALL'),[page,setPage]=useState(0),[selected,setSelected]=useState(addressUuid(initialUnitId)?initialUnitId:'');
 const [loading,setLoading]=useState(false),[sourceLoading,setSourceLoading]=useState(false),[saving,setSaving]=useState(false);
 const [error,setError]=useState(''),[trackerError,setTrackerError]=useState(''),[saveError,setSaveError]=useState(''),[notice,setNotice]=useState(''),[uncertain,setUncertain]=useState(false);
 const [exactPending,setExactPending]=useState<TrackerRequest|null>(null),[pendingDetailError,setPendingDetailError]=useState('');
 const [needsSourceRefresh,setNeedsSourceRefresh]=useState(false);
 const submitted=useRef<ReturnType<typeof trackerRequestPayload>|null>(null);
 const [draft,setDraft]=useState<TrackerDraft|null>(null),[editingSource,setEditingSource]=useState<TrackerSource|null>(null),[confirmed,setConfirmed]=useState(false);
 const detailRef=useRef<HTMLElement|null>(null);
 const running=useRef(false),live=useRef(true),revision=useRef(0),editRevision=useRef(0),requestId=useRef('');
 const refresh=useCallback(async()=>{
  if(!allowed)return null;const request=++revision.current;setLoading(true);
  const [mapResult,trackerResult]=await Promise.allSettled([api.get('/api/field-map'),api.get('/api/unit-tracker')]);
  if(!live.current||request!==revision.current)return null;
  let current:TrackerSnapshot|null=null;
  try{if(trackerResult.status==='rejected')throw trackerResult.reason;current=checkedTrackerSnapshot(trackerResult.value.data);setSnapshot(current);setTrackerError('');}catch(cause){setSnapshot(null);setTrackerError(message(cause));}
  try{if(mapResult.status==='rejected')throw mapResult.reason;setInventory(trackerInventory(mapResult.value.data,current?.sources||[],current?.requests||[]));setError('');}catch(cause){setInventory([]);setError(message(cause));}
  setLoading(false);return current;
 },[allowed]);
 useEffect(()=>{live.current=true;if(allowed)void refresh();return()=>{live.current=false;revision.current++;editRevision.current++;};},[allowed,refresh]);
 useEffect(()=>{if(addressUuid(initialUnitId))setSelected(initialUnitId);},[initialUnitId]);
 const choose=(id:string)=>{if(running.current||draft||sourceLoading)return;setSelected(id);setNotice('');setSaveError('');onSelectUnit?.(id);if(window.matchMedia('(max-width:1100px)').matches)requestAnimationFrame(()=>{detailRef.current?.scrollIntoView({block:'start',behavior:'instant'});detailRef.current?.focus({preventScroll:true});});};
 const cancel=()=>{if(running.current)return;editRevision.current++;setDraft(null);setEditingSource(null);setConfirmed(false);setSaveError('');setNeedsSourceRefresh(false);submitted.current=null;setNotice('Tracker request edits canceled.');requestId.current='';};
 const startAdd=()=>{if(!snapshot?.queueEnabled||running.current||loading)return;setDraft(newTrackerDraft());setEditingSource(null);setConfirmed(false);setUncertain(false);setNeedsSourceRefresh(false);submitted.current=null;setSaveError('');setNotice('');requestId.current=crypto.randomUUID();};
 const startEdit=async(source:TrackerSource)=>{
  if(!snapshot?.queueEnabled||running.current||loading||sourceLoading)return;const request=++editRevision.current;setSourceLoading(true);setSaveError('');setNotice('');
  try{const response=(await api.get('/api/unit-tracker/'+source.unitId)).data;if(response?.queueEnabled!==true)throw new Error('Saving tracker requests is not enabled. Refresh the tracker.');const current=checkedTrackerDetail(response);if(current.pendingRequest){setExactPending(current.pendingRequest);throw new Error('This exact unit already has a saved pending request. Review its pending request below.');}if(current.unitId!==source.unitId)throw new Error('The source unit changed. Refresh before editing.');if(live.current&&request===editRevision.current){setEditingSource(current);setDraft(trackerDraft(current));setConfirmed(false);setUncertain(false);setNeedsSourceRefresh(false);submitted.current=null;requestId.current=crypto.randomUUID();}}
  catch(cause){if(live.current&&request===editRevision.current)setSaveError(message(cause));}finally{if(live.current&&request===editRevision.current)setSourceLoading(false);}
 };
 const update=(key:keyof TrackerDraft,value:string)=>{if(running.current)return;setDraft(current=>current?{...current,[key]:value}:current);setConfirmed(false);setSaveError('');};
 const save=async()=>{
  if(!allowed||!snapshot?.queueEnabled||running.current||loading||uncertain||needsSourceRefresh||!draft||!confirmed)return;
  let payload;try{payload=trackerRequestPayload(draft,editingSource,requestId.current,confirmed);}catch(cause){setSaveError(message(cause));return;}
  submitted.current=payload;running.current=true;setSaving(true);setSaveError('');setNotice('');
  try{
   const result=(await api.post('/api/unit-tracker/requests',payload)).data;
   if(typeof result?.created!=='boolean'||result.ownedByCurrentActor!==true||result.connector?.enabled!==false||result.connector?.state!=='awaiting_sheets_connection')throw new Error('The request save response was incomplete.');
   const receipt=checkedTrackerRequest(result.request);if(!trackerRequestMatches(receipt,payload))throw new Error('The saved request did not match the reviewed fields.');
   const readback=checkedTrackerLookup((await api.get('/api/unit-tracker/requests/'+payload.requestId)).data,payload.requestId);
   if(!readback||!trackerRequestMatches(readback,payload)||readback.createdAt!==receipt.createdAt)throw new Error('The saved request could not be read back.');
   if(live.current){setDraft(null);setEditingSource(null);setConfirmed(false);setUncertain(false);setNotice('Request saved in COS and verified. Sheets connection required; Google Sheets and fleet records have not changed.');show('Tracker request saved. Sheets connection required.');}
   await refresh();
  }catch(cause){if(live.current){setConfirmed(false);if(cause instanceof OperationsApiError&&[400,401,403,409,422].includes(cause.response.status)){setUncertain(false);setNeedsSourceRefresh(cause.response.status!==400&&cause.response.status!==422);setSaveError(message(cause)+' The request was rejected. Your draft is retained for review.');}else{setUncertain(true);setSaveError(message(cause)+' Refresh pending requests before trying again. This request will not be repeated automatically.');}}}
  finally{running.current=false;if(live.current)setSaving(false);}
 };
 const reloadAfterUncertain=async()=>{if(running.current||!submitted.current)return;setLoading(true);try{const payload=submitted.current,found=checkedTrackerLookup((await api.get('/api/unit-tracker/requests/'+payload.requestId)).data,payload.requestId);if(found){if(!trackerRequestMatches(found,payload))throw new Error('The saved request has different fields or identity. It cannot be confirmed as your reviewed request.');setDraft(null);setEditingSource(null);setSaveError('');setUncertain(false);setConfirmed(false);setNotice('The exact reviewed request is saved in COS. Sheets connection required.');await refresh();}else{setUncertain(false);setNeedsSourceRefresh(Boolean(editingSource));setConfirmed(false);setSaveError('No saved request was returned for this request ID. Your draft is retained. Review before retrying; the same request ID will be reused.');}}catch(cause){setSaveError(message(cause)+' The draft remains blocked until its exact save status is verified.');}finally{if(live.current)setLoading(false);}};
 const refreshSourceForReview=async()=>{if(running.current||!draft)return;const intended=trackerChanges(draft,editingSource);setSourceLoading(true);try{if(editingSource){const fresh=checkedTrackerDetail((await api.get('/api/unit-tracker/'+editingSource.unitId)).data);if(fresh.pendingRequest){setExactPending(fresh.pendingRequest);throw new Error('This unit already has a pending request. Review it below or cancel these unsaved edits.');}if(!fresh.queueEnabled)throw new Error('Pending requests are not enabled on this backend.');setDraft({...trackerDraft(fresh),...Object.fromEntries(Object.entries(intended).map(([key,value])=>[key,value??'']))} as TrackerDraft);setEditingSource(fresh);}else{const fresh=await refresh();if(!fresh?.queueEnabled)throw new Error('Pending requests are not enabled on this backend.');}setNeedsSourceRefresh(false);setConfirmed(false);setSaveError('');setNotice('Current source verified. Your changed fields are retained; review them against the refreshed values.');}catch(cause){setSaveError(message(cause)+' Your draft is retained.');}finally{if(live.current)setSourceLoading(false);}};
 const active=inventory.find(row=>row.id===selected),filtered=inventory.filter(row=>(placement==='ALL'||row.placement===placement)&&[row.unitNumber,row.modelName,row.customer,row.site,row.source?.fullVariant,row.source?.family].some(value=>value?.toLowerCase().includes(query.trim().toLowerCase())));
 const pageSize=40,actualPage=Math.min(page,Math.max(0,Math.ceil(filtered.length/pageSize)-1)),visible=filtered.slice(actualPage*pageSize,(actualPage+1)*pageSize),problem=draft?trackerDraftProblem(draft,editingSource):'',changes=draft?trackerChanges(draft,editingSource):{};
 const ownRequests=snapshot?.requests.filter(row=>row.identity.unitId===selected)||[];
 if(exactPending?.identity.unitId===selected&&!ownRequests.some(row=>row.requestId===exactPending.requestId))ownRequests.unshift(exactPending);
 const selectedPendingId=active?.source?.pendingRequestId;
 useEffect(()=>{let activeRequest=true;setExactPending(null);setPendingDetailError('');if(selectedPendingId&&!snapshot?.requests.some(row=>row.requestId===selectedPendingId)){void api.get('/api/unit-tracker/'+selected).then(response=>{const detail=checkedTrackerDetail(response.data);if(detail.unitId!==selected||detail.pendingRequest?.requestId!==selectedPendingId)throw new Error('The pending request changed. Refresh the tracker.');if(activeRequest)setExactPending(detail.pendingRequest);}).catch(cause=>{if(activeRequest)setPendingDetailError(message(cause));});}return()=>{activeRequest=false;};},[selected,selectedPendingId,snapshot]);
 if(!allowed)return <section className='panel module' role='alert'><h2>Unit Tracker unavailable</h2><p>This workspace requires an authorized Owner or verified IT account and a compatible backend.</p></section>;
 return <section className='panel module unit-tracker' aria-label='Unit Tracker workspace'>
  <div className='unit-tracker-heading'><div><h2>One place for your units</h2><p>Current COS inventory and saved requests for the 2027 tracker.</p></div><button className='secondary' disabled={loading||saving||sourceLoading||Boolean(draft)} onClick={()=>void refresh()}>{loading?'Refreshing…':'Refresh tracker'}</button></div>
  <section className='unit-tracker-connection' aria-label='Sheets connection status'><strong>Sheets connection required</strong><p>{snapshot?.queueEnabled?'New units and tracker changes can be saved as pending requests in COS. They have not been sent to Google Sheets or applied to Camera Health or Field View.':'Saving pending additions and tracker changes is not enabled on this backend yet. Existing COS records remain available below.'}</p><a href={'https://docs.google.com/spreadsheets/d/'+trackerWorkbookId+'/edit'} target='_blank' rel='noopener noreferrer'>Open 2027 tracker ↗</a></section>
  {trackerError&&<p className='operations-error' role='alert'>{trackerError} Pending requests and their save controls are unavailable.</p>}{snapshot?.availability==='unavailable'&&<p role='status'>{snapshot.reason||'The pending request store is not ready.'}</p>}
  {error&&<p className='operations-error' role='alert'>{error}</p>}{notice&&<p className='operations-notice' role='status'>{notice}</p>}{saveError&&<p className='operations-error' role='alert'>{saveError}</p>}
  <div className='unit-tracker-toolbar'><button disabled={!snapshot?.queueEnabled||loading||saving||sourceLoading||Boolean(draft)} onClick={startAdd}>+ Add unit request</button><label>Find a unit<input aria-label='Search Unit Tracker' value={query} onChange={event=>{setQuery(event.target.value);setPage(0);}} placeholder='Full unit, model, customer, or site'/></label><label>Placement<select value={placement} onChange={event=>{setPlacement(event.target.value);setPage(0);}}><option value='ALL'>All placements</option>{[...new Set(inventory.map(row=>row.placement))].sort().map(value=><option key={value}>{value}</option>)}</select></label><span>{loading?'Checking inventory…':filtered.length+(filtered.length===1?' unit':' units')}</span></div>
  {draft&&<section className='unit-tracker-form' aria-label={editingSource?'Edit tracker request':'Add unit request'} onKeyDown={event=>{if(event.key==='Escape'){event.stopPropagation();cancel();}}}>
   <div className='unit-tracker-heading'><div><h3>{editingSource?'Request a tracker change':'Request a new unit'}</h3><p>Save the exact fields below as a pending request. A connected, verified Sheets publisher is still required.</p></div><button className='secondary' disabled={saving} onClick={cancel}>Cancel request edits</button></div>
   <fieldset disabled={saving||uncertain}><legend>Equipment identity</legend><div className='unit-tracker-form-grid'>{(['family','fullVariant','unitLabel'] as const).map(key=><label key={key}>{key==='family'?'Family':key==='fullVariant'?'Full model / variant':'Unit label'}<input autoComplete='off' maxLength={key==='unitLabel'?40:160} value={draft[key]} readOnly={Boolean(editingSource)} onChange={event=>update(key,event.target.value)}/></label>)}</div>{editingSource&&<p>Identity is locked to this exact 2027 tracker row. Unit numbers or IP addresses alone are never used to match a unit.</p>}</fieldset>
   <fieldset disabled={saving||uncertain}><legend>Requested tracker fields</legend><div className='unit-tracker-form-grid'><label>Requested placement<select value={draft.placement} onChange={event=>update('placement',event.target.value)}><option value='FIELD'>Field</option><option value='SHOP'>Shop</option><option value='INACTIVE'>Inactive / Do not use</option></select></label>{(['street','city','state','zip','siteLabel','customerLabel'] as const).map(key=><label className={key==='street'?'unit-tracker-wide':''} key={key}>{trackerFieldLabels[key]}<input autoComplete='off' maxLength={key==='street'?300:key==='state'?2:key==='zip'?10:key==='city'?120:250} value={draft[key]} onChange={event=>update(key,event.target.value)}/></label>)}</div><p>Only changed fields are included. Clearing an existing value explicitly requests that field be cleared. No passwords, gate codes, private notes, or spreadsheet formulas.</p></fieldset>
   <section aria-label='Review pending changes'><h4>{editingSource?'Review changes':'Review pending addition'}</h4><dl className='unit-tracker-values'>{Object.entries(changes).map(([key,value])=><div key={key}><dt>{trackerFieldLabels[key as keyof TrackerFields]}</dt><dd>{editingSource&&<><span className='unit-tracker-before'>{display(editingSource.fields[key as keyof TrackerFields])}</span> → </>}{value===null?'Clear this field':String(value)}</dd></div>)}</dl></section>
   {problem&&<p role='status'>{problem}</p>}<label className='unit-tracker-confirm'><input type='checkbox' checked={confirmed} disabled={saving||uncertain||needsSourceRefresh||Boolean(problem)} onChange={event=>setConfirmed(event.target.checked)}/>I reviewed this exact unit and understand this saves a pending request, with Sheets connection still required.</label>
   <div className='unit-tracker-actions'><button disabled={saving||loading||sourceLoading||uncertain||needsSourceRefresh||!confirmed||Boolean(problem)} onClick={()=>void save()}>{saving?'Saving request…':'Save pending request'}</button>{needsSourceRefresh&&!uncertain&&<button className='secondary' disabled={loading||saving||sourceLoading} onClick={()=>void refreshSourceForReview()}>Refresh source and review</button>}{uncertain&&<button className='secondary' disabled={loading||saving} onClick={()=>void reloadAfterUncertain()}>Refresh pending requests</button>}</div>
  </section>}
  <div className='unit-tracker-layout'><section aria-label='Tracked units'><div className='unit-tracker-table-wrap'><table className='unit-tracker-table'><thead><tr><th>Unit / full variant</th><th>Placement</th><th>Customer / site</th><th>Tracker request</th></tr></thead><tbody>{visible.map(row=><tr key={row.id} className={selected===row.id?'selected':''}><td><button className='unit-tracker-unit' aria-pressed={selected===row.id} disabled={saving||Boolean(draft)||sourceLoading} onClick={()=>choose(row.id)}>{row.unitNumber}</button><small>{row.modelName||row.source?.family||'Model not recorded'}</small></td><td>{row.placement}</td><td>{row.customer||row.site||'Not recorded'}{row.customer&&row.site&&<small>{row.site}</small>}</td><td>{row.pending?row.pending+' pending':row.source?'2027 source linked':'Source review needed'}</td></tr>)}</tbody></table></div>{!loading&&!visible.length&&<p>No units match this view.</p>}<div className='unit-tracker-pagination'><button className='secondary' disabled={actualPage===0} onClick={()=>setPage(actualPage-1)}>Previous</button><span>{filtered.length?actualPage*pageSize+1:0}–{Math.min((actualPage+1)*pageSize,filtered.length)} of {filtered.length}</span><button className='secondary' disabled={(actualPage+1)*pageSize>=filtered.length} onClick={()=>setPage(actualPage+1)}>Next</button></div></section>
   <section ref={detailRef} tabIndex={-1} className='unit-tracker-detail' aria-label='Unit Tracker details'>{active?<><h3>{active.unitNumber}</h3><p>{active.source?active.source.family+' · '+active.source.fullVariant:active.modelName||'Current COS unit'}</p><dl className='unit-tracker-values'><div><dt>Current COS placement</dt><dd>{active.placement}</dd></div><div><dt>Customer</dt><dd>{active.customer||'Not recorded'}</dd></div><div><dt>Site</dt><dd>{active.site||'Not recorded'}</dd></div><div><dt>Current COS address</dt><dd>{active.address||'Not recorded'}</dd></div></dl><div className='unit-tracker-actions'><button className='secondary' disabled={Boolean(draft)||saving} onClick={()=>openMap(active.id)}>View in Field View</button><button className='secondary' disabled={Boolean(draft)||saving} onClick={()=>openHealth(active.id)}>View Camera Health</button></div>
    {active.source?<section className='unit-tracker-source'><h4>2027 tracker source</h4><p>{unitName(active.source)} · Imported source values can differ from newer COS corrections.</p><dl className='unit-tracker-values'>{Object.entries(active.source.fields).map(([key,value])=><div key={key}><dt>{trackerFieldLabels[key as keyof TrackerFields]}</dt><dd>{display(value)}</dd></div>)}</dl><button disabled={!snapshot?.queueEnabled||loading||saving||sourceLoading||Boolean(draft)||Boolean(active.source.pendingRequestId)} onClick={()=>void startEdit(active.source!)}>{sourceLoading?'Verifying source…':'Request tracker change'}</button>{active.source.pendingRequestId&&<p role='status'>This exact unit already has a saved pending request. Review it below.</p>}{pendingDetailError&&<p role='alert'>{pendingDetailError} The pending request remains saved; another change is blocked.</p>}</section>:<p>This unit does not have a verified link to an editable 2027 tracker row. Its stable COS record remains visible; a sheet row will not be guessed from its number or IP.</p>}
    {ownRequests.length>0&&<section aria-label='Pending requests for selected unit'><h4>Pending requests for this unit</h4>{ownRequests.map(request=><RequestDetails key={request.requestId} request={request}/>)}</section>}
   </>:<p>{selected?'This unit is not in the current inventory. Refresh or select another exact unit.':'Select a unit to review its current COS data or prepare a tracker change.'}</p>}</section></div>
  <section className='unit-tracker-requests' aria-label='Saved pending tracker requests'><h3>Saved pending requests</h3><p>These requests are retained in COS. None has been published to the 2027 Google Sheet.</p>{snapshot?.requests.length?snapshot.requests.map(request=><RequestDetails key={request.requestId} request={request}/>):<p>{loading?'Checking saved pending requests…':!snapshot?.queueEnabled||snapshot.availability!=='available'||trackerError?'Saved pending requests could not be verified.':'No saved pending requests.'}</p>}{snapshot?.requestsTruncated&&<p role='status'>Showing the most recent 100 requests. Older saved requests are retained.</p>}{Boolean(snapshot?.sourcesHeld)&&<p role='status'>{snapshot!.sourcesHeld} source rows need identity or field review before tracker editing.</p>}{snapshot?.sourcesTruncated&&<p role='status'>The linked-source list reached its limit. Some units need source review before editing.</p>}</section>
 </section>;
}
